great_expectations/_version.py:54: error: Need type annotation for "LONG_VERSION_PY" (hint: "LONG_VERSION_PY: Dict[<type>, <type>] = ...")
great_expectations/datasource/data_connector/asset/asset.py:46: error: Incompatible return value type (got "Optional[str]", expected "str")
great_expectations/datasource/data_connector/asset/asset.py:50: error: Incompatible return value type (got "Optional[str]", expected "str")
great_expectations/datasource/data_connector/asset/asset.py:54: error: Incompatible return value type (got "Optional[str]", expected "str")
great_expectations/datasource/data_connector/asset/asset.py:58: error: Incompatible return value type (got "Optional[List[str]]", expected "List[str]")
great_expectations/datasource/data_connector/asset/asset.py:62: error: Incompatible return value type (got "Optional[str]", expected "str")
great_expectations/datasource/data_connector/asset/asset.py:66: error: Incompatible return value type (got "Optional[str]", expected "str")
great_expectations/datasource/data_connector/asset/asset.py:70: error: Incompatible return value type (got "Optional[str]", expected "str")
great_expectations/datasource/data_connector/asset/asset.py:74: error: Incompatible return value type (got "Optional[int]", expected "int")
great_expectations/core/id_dict.py:6: error: Need type annotation for "_id_ignore_keys" (hint: "_id_ignore_keys: Set[<type>] = ...")
great_expectations/datasource/batch_kwargs_generator/batch_kwargs_generator.py:165: error: Need type annotation for "recognized_batch_parameters" (hint: "recognized_batch_parameters: Set[<type>] = ...")
great_expectations/types/base.py:21: error: Incompatible types in assignment (expression has type "Callable[[Dict[_KT, _VT], _KT, _VT], None]", base class "object" defined the type as "Callable[[object, str, Any], None]")
great_expectations/types/base.py:22: error: Incompatible types in assignment (expression has type "Callable[[Dict[_KT, _VT], _KT], None]", base class "object" defined the type as "Callable[[object, str], None]")
great_expectations/types/base.py:36: error: Need type annotation for "_yaml_merge" (hint: "_yaml_merge: List[<type>] = ...")
great_expectations/expectations/metrics/util.py:65: error: List or tuple literal expected as the second argument to namedtuple()
great_expectations/expectations/metrics/util.py:68: error: Too many arguments for "BigQueryTypes"
great_expectations/expectations/metrics/util.py:200: error: Item "None" of "Optional[List[Dict[str, Any]]]" has no attribute "__iter__" (not iterable)
great_expectations/expectations/metrics/util.py:275: error: Name "col_info_dict_list" already defined on line 247
great_expectations/exceptions/exceptions.py:23: error: Incompatible return value type (got "Union[List[str], List[Any], Dict[Any, Any]]", expected "str")
great_expectations/expectations/row_conditions.py:67: error: Name "pyspark" is not defined
great_expectations/expectations/row_conditions.py:81: error: Incompatible types in assignment (expression has type "float", variable has type "int")
great_expectations/expectations/row_conditions.py:101: error: Name "sqlalchemy" is not defined
great_expectations/expectations/row_conditions.py:115: error: Incompatible types in assignment (expression has type "float", variable has type "int")
great_expectations/core/batch_spec.py:39: error: Incompatible return value type (got "Optional[Any]", expected "str")
great_expectations/core/batch_spec.py:43: error: Incompatible return value type (got "Optional[Any]", expected "str")
great_expectations/render/util.py:179: error: Syntax error in type annotation
great_expectations/render/util.py:179: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
great_expectations/datasource/batch_kwargs_generator/subdir_reader_batch_kwargs_generator.py:41: error: Need type annotation for "_default_reader_options" (hint: "_default_reader_options: Dict[<type>, <type>] = ...")
great_expectations/datasource/batch_kwargs_generator/s3_subdir_reader_batch_kwargs_generator.py:48: error: Need type annotation for "_default_reader_options" (hint: "_default_reader_options: Dict[<type>, <type>] = ...")
great_expectations/expectations/registry.py:11: error: Need type annotation for "_registered_expectations" (hint: "_registered_expectations: Dict[<type>, <type>] = ...")
great_expectations/expectations/registry.py:12: error: Need type annotation for "_registered_metrics" (hint: "_registered_metrics: Dict[<type>, <type>] = ...")
great_expectations/expectations/registry.py:29: error: Name "Expectation" is not defined
great_expectations/expectations/registry.py:32: error: "Callable[..., Any]" has no attribute "_renderer_type"
great_expectations/expectations/registry.py:70: error: Name "Expectation" is not defined
great_expectations/expectations/registry.py:99: error: Name "ExecutionEngine" is not defined
great_expectations/expectations/registry.py:100: error: Name "MetricProvider" is not defined
great_expectations/expectations/registry.py:102: error: Name "MetricFunctionTypes" is not defined
great_expectations/expectations/registry.py:102: error: Name "MetricPartialFunctionTypes" is not defined
great_expectations/expectations/registry.py:106: error: Need type annotation for "res" (hint: "res: Dict[<type>, <type>] = ...")
great_expectations/expectations/registry.py:110: error: "Callable[..., Any]" has no attribute "metric_fn_type"
great_expectations/expectations/registry.py:170: error: Name "ExecutionEngine" is not defined
great_expectations/expectations/registry.py:171: error: Name "MetricProvider" is not defined
great_expectations/expectations/registry.py:182: error: Name "ExecutionEngine" is not defined
great_expectations/expectations/registry.py:183: error: Name "MetricPartialFunctionTypes" is not defined
great_expectations/expectations/registry.py:183: error: Name "MetricFunctionTypes" is not defined
great_expectations/expectations/registry.py:198: error: Name "ExpectationConfiguration" is not defined
great_expectations/expectations/registry.py:261: error: Name "Expectation" is not defined
great_expectations/core/util.py:74: error: Item "Iterable[Any]" of "Union[Iterable[Any], Dict[Any, Any]]" has no attribute "items"
great_expectations/core/util.py:76: error: Unsupported target for indexed assignment ("Union[Iterable[Any], Dict[Any, Any]]")
great_expectations/core/util.py:76: error: Item "Iterable[Any]" of "Union[Iterable[Any], Dict[Any, Any]]" has no attribute "get"
great_expectations/core/util.py:77: error: Value of type "Union[Iterable[Any], Dict[Any, Any]]" is not indexable
great_expectations/core/util.py:78: error: Item "Iterable[Any]" of "Union[Iterable[Any], Dict[Any, Any]]" has no attribute "get"
great_expectations/core/util.py:80: error: Unsupported target for indexed assignment ("Union[Iterable[Any], Dict[Any, Any]]")
great_expectations/core/util.py:81: error: Value of type "Union[Iterable[Any], Dict[Any, Any]]" is not indexable
great_expectations/core/util.py:82: error: Item "Iterable[Any]" of "Union[Iterable[Any], Dict[Any, Any]]" has no attribute "get"
great_expectations/core/util.py:85: error: Unsupported target for indexed assignment ("Union[Iterable[Any], Dict[Any, Any]]")
great_expectations/core/util.py:87: error: Unsupported target for indexed assignment ("Union[Iterable[Any], Dict[Any, Any]]")
great_expectations/core/util.py:89: error: Unsupported target for indexed assignment ("Union[Iterable[Any], Dict[Any, Any]]")
great_expectations/core/util.py:352: error: Name "datetime_obj" already defined on line 344
great_expectations/core/util.py:376: error: Name "datetime_obj" already defined on line 369
great_expectations/core/util.py:377: error: Item "None" of "Optional[datetime]" has no attribute "strftime"
great_expectations/core/util.py:465: error: Incompatible return value type (got "Optional[str]", expected "str")
great_expectations/core/util.py:465: error: Argument 1 to "get" of "Mapping" has incompatible type "Optional[str]"; expected "str"
great_expectations/data_context/types/base.py:1266: error: Value of type "Union[object, Any]" is not indexable
great_expectations/data_context/types/base.py:1269: error: Value of type "Union[object, Any]" is not indexable
great_expectations/data_context/types/base.py:1272: error: Value of type "Union[object, Any]" is not indexable
great_expectations/data_context/types/base.py:1275: error: Unsupported target for indexed assignment ("Union[object, Any]")
great_expectations/data_context/types/base.py:1558: error: Incompatible types in assignment (expression has type "Dict[<nothing>, <nothing>]", variable has type "Union[Dict[str, DatasourceConfig], Dict[str, Dict[str, Union[Dict[str, str], str, Dict[Any, Any]]]], None]")
great_expectations/data_context/types/base.py:1835: error: Argument 2 to "nested_update" has incompatible type "Optional[Any]"; expected "Union[Iterable[Any], Dict[Any, Any]]"
great_expectations/data_context/types/base.py:1840: error: Argument "other_action_list" to "get_updated_action_list" of "CheckpointConfig" has incompatible type "Optional[Any]"; expected "List[Any]"
great_expectations/data_context/types/base.py:1845: error: Argument 2 to "nested_update" has incompatible type "Optional[Any]"; expected "Union[Iterable[Any], Dict[Any, Any]]"
great_expectations/data_context/types/base.py:1850: error: Argument 2 to "nested_update" has incompatible type "Optional[Any]"; expected "Union[Iterable[Any], Dict[Any, Any]]"
great_expectations/data_context/types/base.py:1856: error: Argument 2 to "filter" has incompatible type "Optional[Any]"; expected "Iterable[Any]"
great_expectations/validation_operators/types/validation_operator_result.py:55: error: Item "Dict[Any, Any]" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any], str]" has no attribute "success"
great_expectations/validation_operators/types/validation_operator_result.py:55: error: Item "str" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any], str]" has no attribute "success"
great_expectations/validation_operators/types/validation_operator_result.py:86: error: Incompatible return value type (got "Dict[ValidationResultIdentifier, Dict[str, Union[ExpectationSuiteValidationResult, Dict[Any, Any], str]]]", expected "Dict[ValidationResultIdentifier, Dict[str, Union[ExpectationSuiteValidationResult, Dict[Any, Any]]]]")
great_expectations/validation_operators/types/validation_operator_result.py:102: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "None")
great_expectations/validation_operators/types/validation_operator_result.py:108: error: Incompatible return value type (got "None", expected "List[str]")
great_expectations/validation_operators/types/validation_operator_result.py:112: error: Incompatible types in assignment (expression has type "List[Union[Any, str]]", variable has type "None")
great_expectations/validation_operators/types/validation_operator_result.py:118: error: Incompatible return value type (got "None", expected "List[str]")
great_expectations/validation_operators/types/validation_operator_result.py:122: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "None")
great_expectations/validation_operators/types/validation_operator_result.py:128: error: Incompatible return value type (got "None", expected "List[str]")
great_expectations/validation_operators/types/validation_operator_result.py:132: error: Incompatible types in assignment (expression has type "List[ValidationResultIdentifier]", variable has type "None")
great_expectations/validation_operators/types/validation_operator_result.py:133: error: Incompatible return value type (got "None", expected "List[ValidationResultIdentifier]")
great_expectations/validation_operators/types/validation_operator_result.py:135: error: Missing return statement
great_expectations/validation_operators/types/validation_operator_result.py:141: error: Incompatible types in assignment (expression has type "List[Union[ExpectationSuiteValidationResult, Dict[Any, Any]]]", variable has type "None")
great_expectations/validation_operators/types/validation_operator_result.py:144: error: Incompatible return value type (got "None", expected "Union[List[ExpectationSuiteValidationResult], Dict[Any, Any]]")
great_expectations/validation_operators/types/validation_operator_result.py:154: error: Incompatible types in assignment (expression has type "Dict[ValidationResultIdentifier, Union[ExpectationSuiteValidationResult, Dict[Any, Any]]]", variable has type "None")
great_expectations/validation_operators/types/validation_operator_result.py:158: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")
great_expectations/validation_operators/types/validation_operator_result.py:162: error: Incompatible types in assignment (expression has type "Dict[str, List[Union[ExpectationSuiteValidationResult, Dict[Any, Any]]]]", variable has type "None")
great_expectations/validation_operators/types/validation_operator_result.py:166: error: Item "Dict[Any, Any]" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any]]" has no attribute "meta"
great_expectations/validation_operators/types/validation_operator_result.py:171: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")
great_expectations/validation_operators/types/validation_operator_result.py:191: error: Incompatible types in assignment (expression has type "Dict[str, List[Any]]", variable has type "None")
great_expectations/validation_operators/types/validation_operator_result.py:193: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")
great_expectations/validation_operators/types/validation_operator_result.py:195: error: Missing return statement
great_expectations/validation_operators/types/validation_operator_result.py:200: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "None")
great_expectations/validation_operators/types/validation_operator_result.py:203: error: Incompatible return value type (got "None", expected "Union[List[Dict[Any, Any]], Dict[Any, Any]]")
great_expectations/validation_operators/types/validation_operator_result.py:230: error: Incompatible types in assignment (expression has type "Dict[Any, Dict[str, Any]]", variable has type "None")
great_expectations/validation_operators/types/validation_operator_result.py:231: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")
great_expectations/validation_operators/types/validation_operator_result.py:252: error: Incompatible types in assignment (expression has type "Dict[str, object]", variable has type "None")
great_expectations/validation_operators/types/validation_operator_result.py:261: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")
great_expectations/validation_operators/types/validation_operator_result.py:265: error: Incompatible types in assignment (expression has type "Dict[ValidationResultIdentifier, Any]", variable has type "None")
great_expectations/validation_operators/types/validation_operator_result.py:266: error: Item "Dict[Any, Any]" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any]]" has no attribute "statistics"
great_expectations/validation_operators/types/validation_operator_result.py:269: error: Incompatible return value type (got "None", expected "Dict[ValidationResultIdentifier, Dict[Any, Any]]")
great_expectations/checkpoint/types/checkpoint_result.py:68: error: Item "Dict[Any, Any]" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any], str]" has no attribute "success"
great_expectations/checkpoint/types/checkpoint_result.py:68: error: Item "str" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any], str]" has no attribute "success"
great_expectations/checkpoint/types/checkpoint_result.py:103: error: Incompatible return value type (got "Dict[ValidationResultIdentifier, Dict[str, Union[ExpectationSuiteValidationResult, Dict[Any, Any], str]]]", expected "Dict[ValidationResultIdentifier, Dict[str, Union[ExpectationSuiteValidationResult, Dict[Any, Any]]]]")
great_expectations/checkpoint/types/checkpoint_result.py:115: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "None")
great_expectations/checkpoint/types/checkpoint_result.py:121: error: Incompatible return value type (got "None", expected "List[str]")
great_expectations/checkpoint/types/checkpoint_result.py:125: error: Incompatible types in assignment (expression has type "List[Union[Any, str]]", variable has type "None")
great_expectations/checkpoint/types/checkpoint_result.py:131: error: Incompatible return value type (got "None", expected "List[str]")
great_expectations/checkpoint/types/checkpoint_result.py:135: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "None")
great_expectations/checkpoint/types/checkpoint_result.py:141: error: Incompatible return value type (got "None", expected "List[str]")
great_expectations/checkpoint/types/checkpoint_result.py:145: error: Incompatible types in assignment (expression has type "List[ValidationResultIdentifier]", variable has type "None")
great_expectations/checkpoint/types/checkpoint_result.py:146: error: Incompatible return value type (got "None", expected "List[ValidationResultIdentifier]")
great_expectations/checkpoint/types/checkpoint_result.py:148: error: Missing return statement
great_expectations/checkpoint/types/checkpoint_result.py:154: error: Incompatible types in assignment (expression has type "List[Union[ExpectationSuiteValidationResult, Dict[Any, Any]]]", variable has type "None")
great_expectations/checkpoint/types/checkpoint_result.py:157: error: Incompatible return value type (got "None", expected "Union[List[ExpectationSuiteValidationResult], Dict[Any, Any]]")
great_expectations/checkpoint/types/checkpoint_result.py:167: error: Incompatible types in assignment (expression has type "Dict[ValidationResultIdentifier, Union[ExpectationSuiteValidationResult, Dict[Any, Any]]]", variable has type "None")
great_expectations/checkpoint/types/checkpoint_result.py:171: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")
great_expectations/checkpoint/types/checkpoint_result.py:175: error: Incompatible types in assignment (expression has type "Dict[str, List[Union[ExpectationSuiteValidationResult, Dict[Any, Any]]]]", variable has type "None")
great_expectations/checkpoint/types/checkpoint_result.py:179: error: Item "Dict[Any, Any]" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any]]" has no attribute "meta"
great_expectations/checkpoint/types/checkpoint_result.py:184: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")
great_expectations/checkpoint/types/checkpoint_result.py:204: error: Incompatible types in assignment (expression has type "Dict[str, List[Any]]", variable has type "None")
great_expectations/checkpoint/types/checkpoint_result.py:206: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")
great_expectations/checkpoint/types/checkpoint_result.py:208: error: Missing return statement
great_expectations/checkpoint/types/checkpoint_result.py:213: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "None")
great_expectations/checkpoint/types/checkpoint_result.py:216: error: Incompatible return value type (got "None", expected "Union[List[Dict[Any, Any]], Dict[Any, Any]]")
great_expectations/checkpoint/types/checkpoint_result.py:245: error: Incompatible types in assignment (expression has type "Dict[Any, Dict[str, Any]]", variable has type "None")
great_expectations/checkpoint/types/checkpoint_result.py:246: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")
great_expectations/checkpoint/types/checkpoint_result.py:267: error: Incompatible types in assignment (expression has type "Dict[str, object]", variable has type "None")
great_expectations/checkpoint/types/checkpoint_result.py:276: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")
great_expectations/checkpoint/types/checkpoint_result.py:280: error: Incompatible types in assignment (expression has type "Dict[ValidationResultIdentifier, Any]", variable has type "None")
great_expectations/checkpoint/types/checkpoint_result.py:281: error: Item "Dict[Any, Any]" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any]]" has no attribute "statistics"
great_expectations/checkpoint/types/checkpoint_result.py:284: error: Incompatible return value type (got "None", expected "Dict[ValidationResultIdentifier, Dict[Any, Any]]")
great_expectations/util.py:46: error: Name "importlib_metadata" already defined (by an import)
great_expectations/util.py:123: error: Argument 1 to "wraps" has incompatible type "Optional[Callable[..., Any]]"; expected "Callable[..., Any]"
great_expectations/util.py:127: error: "None" not callable
great_expectations/util.py:140: error: Argument 1 to "wraps" has incompatible type "Optional[Callable[..., Any]]"; expected "Callable[..., Any]"
great_expectations/util.py:144: error: "None" not callable
great_expectations/util.py:148: error: Argument 1 to "signature" has incompatible type "Optional[Callable[..., Any]]"; expected "Callable[..., Any]"
great_expectations/util.py:151: error: Item "None" of "Optional[Callable[..., Any]]" has no attribute "__name__"
great_expectations/util.py:160: error: Module has no attribute "distributions"
great_expectations/util.py:174: error: Incompatible types in assignment (expression has type "Optional[FrameType]", variable has type "FrameType")
great_expectations/util.py:175: error: Incompatible types in assignment (expression has type "Optional[FrameType]", variable has type "FrameType")
great_expectations/util.py:207: error: Incompatible types in assignment (expression has type "Optional[FrameType]", variable has type "FrameType")
great_expectations/util.py:208: error: Incompatible types in assignment (expression has type "Optional[FrameType]", variable has type "FrameType")
great_expectations/util.py:242: error: Item "None" of "Optional[Module]" has no attribute "__name__"
great_expectations/util.py:262: error: Incompatible types in assignment (expression has type "Optional[ModuleSpec]", variable has type "ModuleSpec")
great_expectations/util.py:266: error: Incompatible types in assignment (expression has type "None", variable has type "ModuleSpec")
great_expectations/validator/validator.py:301: error: Need type annotation for "resolved_metrics" (hint: "resolved_metrics: Dict[<type>, <type>] = ...")
great_expectations/validator/validator.py:478: error: Argument 1 to "metrics_validate" of "ExpectationConfiguration" has incompatible type "Optional[Dict[Any, Any]]"; expected "Dict[Any, Any]"
great_expectations/validator/validator.py:607: error: Item "None" of "Optional[ExpectationSuite]" has no attribute "expectation_suite_name"
great_expectations/validator/validator.py:612: error: Item "None" of "Optional[ExpectationSuite]" has no attribute "expectation_suite_name"
great_expectations/validator/validator.py:616: error: Item "None" of "Optional[ExpectationSuite]" has no attribute "expectation_suite_name"
great_expectations/validator/validator.py:625: error: Item "None" of "Optional[ExpectationSuite]" has no attribute "execution_engine_type"
great_expectations/validator/validator.py:649: error: Item "None" of "Optional[ExpectationSuite]" has no attribute "find_expectation_indexes"
great_expectations/validator/validator.py:664: error: Item "None" of "Optional[ExpectationSuite]" has no attribute "find_expectations"
great_expectations/validator/validator.py:680: error: Item "None" of "Optional[ExpectationSuite]" has no attribute "remove_expectation"
great_expectations/validator/validator.py:717: error: Incompatible types in assignment (expression has type "Optional[Batch]", variable has type "Batch")
great_expectations/validation_operators/validation_operators.py:237: error: Incompatible types in assignment (expression has type "Dict[str, Any]", variable has type "None")
great_expectations/validation_operators/validation_operators.py:246: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")
great_expectations/validation_operators/validation_operators.py:591: error: Incompatible types in assignment (expression has type "Dict[str, Any]", variable has type "None")
great_expectations/validation_operators/validation_operators.py:606: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")
great_expectations/validation_operators/validation_operators.py:630: error: Item "Dict[Any, Any]" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any]]" has no attribute "success"
great_expectations/profile/basic_dataset_profiler.py:27: error: Cannot determine type of "INT_TYPE_NAMES"
great_expectations/profile/basic_dataset_profiler.py:28: error: Cannot determine type of "FLOAT_TYPE_NAMES"
great_expectations/profile/basic_dataset_profiler.py:29: error: Cannot determine type of "STRING_TYPE_NAMES"
great_expectations/profile/basic_dataset_profiler.py:30: error: Cannot determine type of "BOOLEAN_TYPE_NAMES"
great_expectations/profile/basic_dataset_profiler.py:31: error: Cannot determine type of "DATETIME_TYPE_NAMES"
great_expectations/execution_engine/sqlalchemy_execution_engine.py:103: error: List or tuple literal expected as the second argument to namedtuple()
great_expectations/execution_engine/sqlalchemy_execution_engine.py:106: error: Too many arguments for "BigQueryTypes"
great_expectations/execution_engine/sqlalchemy_execution_engine.py:605: error: Need more than 4 values to unpack (5 expected)
great_expectations/execution_engine/sqlalchemy_execution_engine.py:612: error: Cannot determine type of "compute_domain_kwargs"
great_expectations/execution_engine/sqlalchemy_execution_engine.py:613: error: Cannot determine type of "compute_domain_kwargs"
great_expectations/execution_engine/sqlalchemy_execution_engine.py:622: error: Cannot determine type of "engine_fn"
great_expectations/execution_engine/sqlalchemy_execution_engine.py:622: error: Cannot determine type of "metric_to_resolve"
great_expectations/execution_engine/sqlalchemy_execution_engine.py:624: error: Cannot determine type of "metric_to_resolve"
great_expectations/execution_engine/sqlalchemy_execution_engine.py:626: error: Incompatible types in assignment (expression has type "Dict[Any, Any]", variable has type "IDDict")
great_expectations/execution_engine/sqlalchemy_execution_engine.py:897: error: Name "selectable" already defined on line 893
great_expectations/execution_engine/sparkdf_execution_engine.py:529: error: Need more than 3 values to unpack (5 expected)
great_expectations/execution_engine/sparkdf_execution_engine.py:536: error: Cannot determine type of "compute_domain_kwargs"
great_expectations/execution_engine/sparkdf_execution_engine.py:537: error: Cannot determine type of "compute_domain_kwargs"
great_expectations/execution_engine/sparkdf_execution_engine.py:545: error: Cannot determine type of "engine_fn"
great_expectations/execution_engine/sparkdf_execution_engine.py:546: error: Cannot determine type of "metric_to_resolve"
great_expectations/execution_engine/pandas_execution_engine.py:167: error: Name "reader_method" already defined on line 150
great_expectations/execution_engine/pandas_execution_engine.py:168: error: Name "reader_options" already defined on line 151
great_expectations/execution_engine/pandas_execution_engine.py:170: error: Name "reader_fn" already defined on line 162
great_expectations/execution_engine/execution_engine.py:61: error: Need type annotation for "recognized_batch_spec_defaults" (hint: "recognized_batch_spec_defaults: Set[<type>] = ...")
great_expectations/execution_engine/execution_engine.py:226: error: Need type annotation for "metric_fn_bundle" (hint: "metric_fn_bundle: List[<type>] = ...")
great_expectations/datasource/sqlalchemy_datasource.py:43: error: Incompatible types in assignment (expression has type "Tuple[Any, Any, Any]", variable has type "Tuple[Any, Any, Any, Any]")
great_expectations/datasource/simple_sqlalchemy_datasource.py:38: error: Need type annotation for "_data_connectors" (hint: "_data_connectors: Dict[<type>, <type>] = ...")
great_expectations/datasource/simple_sqlalchemy_datasource.py:45: error: Need type annotation for "_datasource_config" (hint: "_datasource_config: Dict[<type>, <type>] = ...")
great_expectations/datasource/new_datasource.py:58: error: Need type annotation for "_data_connectors" (hint: "_data_connectors: Dict[<type>, <type>] = ...")
great_expectations/datasource/new_datasource.py:159: error: Unexpected keyword argument "runtime_parameters" for "get_batch_data_and_metadata" of "DataConnector"
great_expectations/datasource/new_datasource.py:179: error: Name "batch_data" already defined on line 156
great_expectations/datasource/new_datasource.py:180: error: Name "batch_spec" already defined on line 157
great_expectations/datasource/new_datasource.py:181: error: Name "batch_markers" already defined on line 158
great_expectations/datasource/new_datasource.py:189: error: Name "new_batch" already defined on line 164
great_expectations/datasource/data_connector/data_connector.py:82: note: "get_batch_data_and_metadata" of "DataConnector" defined here
great_expectations/datasource/new_datasource.py:159: error: Unexpected keyword argument "runtime_parameters" for "get_batch_data_and_metadata" of "DataConnector"
great_expectations/datasource/data_connector/data_connector.py:82: note: "get_batch_data_and_metadata" of "DataConnector" defined here
great_expectations/datasource/new_datasource.py:159: error: Unexpected keyword argument "runtime_parameters" for "get_batch_data_and_metadata" of "DataConnector"
great_expectations/datasource/new_datasource.py:249: error: Incompatible types in assignment (expression has type "KeysView[Any]", variable has type "Union[List[Any], str, None]")
great_expectations/datasource/new_datasource.py:253: error: Item "None" of "Optional[List[Any]]" has no attribute "__iter__" (not iterable)
great_expectations/datasource/data_connector/data_connector.py:82: note: "get_batch_data_and_metadata" of "DataConnector" defined here
great_expectations/datasource/new_datasource.py:159: error: Unexpected keyword argument "runtime_parameters" for "get_batch_data_and_metadata" of "DataConnector"
great_expectations/datasource/data_connector/data_connector.py:82: note: "get_batch_data_and_metadata" of "DataConnector" defined here
great_expectations/datasource/new_datasource.py:217: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")
great_expectations/datasource/data_connector/util.py:229: error: "SubPattern" has no attribute "__iter__" (not iterable)
great_expectations/datasource/data_connector/util.py:262: error: Name "data_reference_template" already defined on line 222
great_expectations/datasource/data_connector/util.py:293: error: The return type of a generator function should be "Generator" or one of its supertypes
great_expectations/datasource/data_connector/runtime_data_connector.py:85: error: Incompatible return value type (got "List[List[str]]", expected "List[str]")
great_expectations/datasource/data_connector/runtime_data_connector.py:118: error: Signature of "get_batch_data_and_metadata" incompatible with supertype "DataConnector"
great_expectations/datasource/data_connector/runtime_data_connector.py:123: error: Incompatible types in assignment (expression has type "Union[RuntimeDataBatchSpec, RuntimeQueryBatchSpec, PathBatchSpec]", variable has type "RuntimeDataBatchSpec")
great_expectations/datasource/data_connector/runtime_data_connector.py:127: error: Item "None" of "Optional[ExecutionEngine]" has no attribute "get_batch_data_and_markers"
great_expectations/datasource/data_connector/runtime_data_connector.py:131: error: Incompatible return value type (got "Tuple[Union[BatchData, Any], RuntimeDataBatchSpec, Union[great_expectations.core.batch.BatchMarkers, Any]]", expected "Tuple[Any, BatchSpec, great_expectations.core.batch_spec.BatchMarkers]")
great_expectations/datasource/data_connector/runtime_data_connector.py:136: error: Argument 1 of "get_batch_definition_list_from_batch_request" is incompatible with supertype "DataConnector"; supertype defines the argument type as "BatchRequest"
great_expectations/datasource/data_connector/runtime_data_connector.py:136: note: This violates the Liskov substitution principle
great_expectations/datasource/data_connector/runtime_data_connector.py:136: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
great_expectations/datasource/data_connector/runtime_data_connector.py:179: error: Argument 3 to "_update_data_references_cache" of "RuntimeDataConnector" has incompatible type "Dict[Any, Any]"; expected "IDDict"
great_expectations/datasource/data_connector/runtime_data_connector.py:218: error: Missing return statement
great_expectations/datasource/data_connector/runtime_data_connector.py:218: error: Signature of "build_batch_spec" incompatible with supertype "DataConnector"
great_expectations/datasource/data_connector/runtime_data_connector.py:237: error: Unsupported operand types for in ("str" and "bytes")
great_expectations/datasource/data_connector/runtime_data_connector.py:254: error: Invalid type comment or annotation
great_expectations/datasource/data_connector/runtime_data_connector.py:254: note: Suggestion: use type[...] instead of type(...)
great_expectations/datasource/data_connector/runtime_data_connector.py:273: error: Argument "batch_request" to "_validate_batch_request" of "DataConnector" has incompatible type "BatchRequestBase"; expected "BatchRequest"
great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py:83: error: Need type annotation for "_introspected_assets_cache" (hint: "_introspected_assets_cache: Dict[<type>, <type>] = ...")
great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py:87: error: Argument 3 to "_refresh_introspected_assets_cache" of "InferredAssetSqlDataConnector" has incompatible type "Optional[bool]"; expected "bool"
great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py:94: error: Argument 10 to "_refresh_introspected_assets_cache" of "InferredAssetSqlDataConnector" has incompatible type "Optional[bool]"; expected "bool"
great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py:98: error: Return type "Dict[str, Asset]" of "assets" incompatible with return type "Dict[str, Dict[Any, Any]]" in supertype "ConfiguredAssetSqlDataConnector"
great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py:209: error: Item "ExecutionEngine" of "Optional[ExecutionEngine]" has no attribute "engine"
great_expectations/datasource/data_connector/inferred_asset_sql_data_connector.py:209: error: Item "None" of "Optional[ExecutionEngine]" has no attribute "engine"
great_expectations/datasource/data_connector/inferred_asset_s3_data_connector.py:80: error: Argument 1 to "join" has incompatible type "Optional[str]"; expected "Union[str, PathLike[str]]"
great_expectations/datasource/data_connector/inferred_asset_filesystem_data_connector.py:77: error: Argument "glob_directive" to "get_filesystem_one_level_directory_glob_path_list" has incompatible type "Optional[str]"; expected "str"
great_expectations/datasource/data_connector/file_path_data_connector.py:73: error: Argument "config_list" to "build_sorters_from_config" has incompatible type "Optional[List[Any]]"; expected "List[Dict[str, Any]]"
great_expectations/datasource/data_connector/file_path_data_connector.py:98: error: Argument 1 to "len" has incompatible type "Optional[Dict[Any, Any]]"; expected "Sized"
great_expectations/datasource/data_connector/file_path_data_connector.py:168: error: Argument 1 to "len" has incompatible type "Optional[Dict[Any, Any]]"; expected "Sized"
great_expectations/datasource/data_connector/file_path_data_connector.py:196: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "values"
great_expectations/datasource/data_connector/file_path_data_connector.py:264: error: Argument "batch_request" to "_validate_batch_request" of "DataConnector" has incompatible type "BatchRequestBase"; expected "BatchRequest"
great_expectations/datasource/data_connector/data_connector.py:57: error: Need type annotation for "_data_references_cache" (hint: "_data_references_cache: Dict[<type>, <type>] = ...")
great_expectations/datasource/data_connector/data_connector.py:76: error: Incompatible return value type (got "None", expected "str")
great_expectations/datasource/data_connector/data_connector.py:80: error: Incompatible types in assignment (expression has type "str", variable has type "None")
great_expectations/datasource/data_connector/data_connector.py:95: error: Item "None" of "Optional[ExecutionEngine]" has no attribute "get_batch_data_and_markers"
great_expectations/datasource/data_connector/data_connector.py:98: error: Item "None" of "Optional[ExecutionEngine]" has no attribute "load_batch_data"
great_expectations/datasource/data_connector/data_connector.py:331: error: Incompatible types in assignment (expression has type "Optional[List[BatchDefinition]]", variable has type "List[BatchDefinition]")
great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py:183: error: Argument "data_asset_name" to "BatchDefinition" has incompatible type "Optional[str]"; expected "str"
great_expectations/datasource/data_connector/configured_asset_s3_data_connector.py:82: error: Argument 1 to "join" has incompatible type "Optional[str]"; expected "Union[str, PathLike[str]]"
great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py:142: error: Argument "data_asset_name" to "_get_asset" of "ConfiguredAssetFilePathDataConnector" has incompatible type "Optional[str]"; expected "str"
great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py:217: error: Incompatible types in assignment (expression has type "Union[Dict[Any, Any], Asset]", variable has type "Optional[Asset]")
great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py:218: error: Incompatible return value type (got "Optional[Asset]", expected "Asset")
great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py:240: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Asset]" has no attribute "batch_spec_passthrough"
great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py:241: error: Item "Dict[Any, Any]" of "Union[Dict[Any, Any], Asset]" has no attribute "batch_spec_passthrough"
great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py:245: error: Value of type "Union[Dict[Any, Any], Asset]" is not indexable
great_expectations/datasource/data_connector/batch_filter.py:45: error: Incompatible types in assignment (expression has type "Union[int, List[Any], Tuple[Any, ...], slice, str, Dict[Any, Any], Callable[..., Any], None]", variable has type "Callable[..., Any]")
great_expectations/datasource/data_connector/batch_filter.py:48: error: Argument 2 to "isinstance" has incompatible type "_SpecialForm"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"
great_expectations/datasource/data_connector/batch_filter.py:56: error: Incompatible types in assignment (expression has type "Union[int, List[Any], Tuple[Any, ...], slice, str, Dict[Any, Any], Callable[..., Any], None]", variable has type "Union[Dict[Any, Any], IDDict, None]")
great_expectations/datasource/data_connector/batch_filter.py:71: error: Incompatible types in assignment (expression has type "Union[int, List[Any], Tuple[Any, ...], slice, str, Dict[Any, Any], Callable[..., Any], None]", variable has type "Union[int, List[Any], Tuple[Any, ...], slice, str, None]")
great_expectations/datasource/data_connector/batch_filter.py:72: error: Incompatible types in assignment (expression has type "Union[int, List[Any], Tuple[Any, ...], slice, str, Dict[Any, Any], Callable[..., Any], None]", variable has type "Optional[int]")
great_expectations/datasource/data_connector/batch_filter.py:86: error: Argument "batch_filter_parameters" to "BatchFilter" has incompatible type "Optional[Dict[Any, Any]]"; expected "Optional[IDDict]"
great_expectations/datasource/data_connector/batch_filter.py:92: error: Missing return statement
great_expectations/datasource/data_connector/batch_filter.py:115: error: Optional[...] must have exactly one type argument
great_expectations/datasource/data_connector/batch_filter.py:156: error: Incompatible return value type (got "Optional[Callable[..., Any]]", expected "Callable[..., Any]")
great_expectations/datasource/data_connector/batch_filter.py:168: error: Incompatible return value type (got "Optional[int]", expected "int")
great_expectations/datasource/data_connector/sorter/sorter.py:16: error: Name "reverse" already defined on line 14
great_expectations/dataset/sqlalchemy_dataset.py:109: error: List or tuple literal expected as the second argument to namedtuple()
great_expectations/dataset/sqlalchemy_dataset.py:112: error: Too many arguments for "BigQueryTypes"
great_expectations/dataset/sqlalchemy_dataset.py:133: error: Incompatible types in assignment (expression has type "None", variable has type Module)
great_expectations/dataset/sqlalchemy_dataset.py:370: error: "MetaSqlAlchemyDataset" has no attribute "engine"
great_expectations/dataset/sqlalchemy_dataset.py:371: error: "MetaSqlAlchemyDataset" has no attribute "engine"
great_expectations/dataset/sqlalchemy_dataset.py:377: error: "MetaSqlAlchemyDataset" has no attribute "engine"
great_expectations/dataset/sqlalchemy_dataset.py:395: error: "MetaSqlAlchemyDataset" has no attribute "_table"
great_expectations/dataset/sqlalchemy_dataset.py:397: error: "MetaSqlAlchemyDataset" has no attribute "engine"
great_expectations/dataset/sqlalchemy_dataset.py:408: error: "MetaSqlAlchemyDataset" has no attribute "_table"
great_expectations/dataset/sqlalchemy_dataset.py:458: error: "MetaSqlAlchemyDataset" has no attribute "_table"
great_expectations/dataset/sqlalchemy_dataset.py:911: error: Missing return statement
great_expectations/dataset/sqlalchemy_dataset.py:927: error: Missing return statement
great_expectations/dataset/sqlalchemy_dataset.py:943: error: Missing return statement
great_expectations/dataset/sqlalchemy_dataset.py:957: error: Missing return statement
great_expectations/dataset/sqlalchemy_dataset.py:1011: error: Missing return statement
great_expectations/dataset/sqlalchemy_dataset.py:1037: error: Name "quantiles_results" already defined on line 1021
great_expectations/dataset/sparkdf_dataset.py:1201: error: Signature of "expect_column_values_to_be_in_type_list" incompatible with supertype "Dataset"
great_expectations/dataset/sparkdf_dataset.py:1241: error: Incompatible types in assignment (expression has type "Tuple[Any, ...]", variable has type "List[Any]")
great_expectations/dataset/sparkdf_dataset.py:1242: error: Argument 2 to "issubclass" has incompatible type "List[Any]"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"
great_expectations/data_context/util.py:19: error: Cannot assign to a type
great_expectations/data_context/util.py:19: error: Incompatible types in assignment (expression has type "None", variable has type "Type[DefaultAzureCredential]")
great_expectations/data_context/util.py:31: error: Incompatible types in assignment (expression has type "None", variable has type Module)
great_expectations/data_context/data_context.py:647: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "keys"
great_expectations/data_context/data_context.py:683: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "items"
great_expectations/data_context/data_context.py:990: error: Item "CommentedMap" of "Union[DataContextConfig, CommentedMap, Dict[Any, Any], str]" has no attribute "config_variables_file_path"
great_expectations/data_context/data_context.py:990: error: Item "Dict[Any, Any]" of "Union[DataContextConfig, CommentedMap, Dict[Any, Any], str]" has no attribute "config_variables_file_path"
great_expectations/data_context/data_context.py:990: error: Item "str" of "Union[DataContextConfig, CommentedMap, Dict[Any, Any], str]" has no attribute "config_variables_file_path"
great_expectations/data_context/data_context.py:1193: error: Argument 1 to "get_datasource" of "BaseDataContext" has incompatible type "Optional[Any]"; expected "str"
great_expectations/data_context/data_context.py:1194: error: Item "BaseDatasource" of "Union[LegacyDatasource, BaseDatasource, None]" has no attribute "get_batch"
great_expectations/data_context/data_context.py:1194: error: Item "None" of "Union[LegacyDatasource, BaseDatasource, None]" has no attribute "get_batch"
great_expectations/data_context/data_context.py:1198: error: Item "None" of "Union[LegacyDatasource, BaseDatasource, None]" has no attribute "config"
great_expectations/data_context/data_context.py:1409: error: Incompatible types in assignment (expression has type "Union[LegacyDatasource, BaseDatasource, None]", variable has type "Union[LegacyDatasource, BaseDatasource]")
great_expectations/data_context/data_context.py:1423: error: Name "datasource" already defined on line 1409
great_expectations/data_context/data_context.py:1566: error: Name "datasource_name" already defined on line 1500
great_expectations/data_context/data_context.py:1574: error: Invalid index type "Optional[str]" for "Dict[str, Union[LegacyDatasource, BaseDatasource]]"; expected type "str"
great_expectations/data_context/data_context.py:1672: error: Name "batch_request" already defined on line 1500
great_expectations/data_context/data_context.py:1679: error: Argument "batch_request" to "get_batch_list_from_batch_request" of "BaseDatasource" has incompatible type "Optional[BatchRequest]"; expected "Union[BatchRequest, RuntimeBatchRequest]"
great_expectations/data_context/data_context.py:1781: error: Item "LegacyDatasource" of "Union[LegacyDatasource, BaseDatasource]" has no attribute "execution_engine"
great_expectations/data_context/data_context.py:1822: error: Argument "class_name" to "load_class" has incompatible type "Optional[Any]"; expected "str"
great_expectations/data_context/data_context.py:1832: error: Incompatible return value type (got "Union[LegacyDatasource, BaseDatasource, None]", expected "Optional[Dict[str, Union[LegacyDatasource, BaseDatasource]]]")
great_expectations/data_context/data_context.py:1845: error: Value of type "Union[Dict[str, DatasourceConfig], Dict[str, Dict[str, Union[Dict[str, str], str, Dict[Any, Any]]]], None]" is not indexable
great_expectations/data_context/data_context.py:1845: error: Incompatible types in assignment (expression has type "Union[DatasourceConfig, Dict[str, Union[Dict[str, str], str, Dict[Any, Any]]], Any]", variable has type "DatasourceConfig")
great_expectations/data_context/data_context.py:1848: error: Name "config" already defined on line 1838
great_expectations/data_context/data_context.py:1940: error: Item "DatasourceConfig" of "Union[Dict[Any, Any], DatasourceConfig]" has no attribute "update"
great_expectations/data_context/data_context.py:1946: error: Item "DatasourceConfig" of "Union[Dict[Any, Any], DatasourceConfig]" has no attribute "update"
great_expectations/data_context/data_context.py:1975: error: Unsupported right operand type for in ("Union[Dict[str, DatasourceConfig], Dict[str, Dict[str, Union[Dict[str, str], str, Dict[Any, Any]]]], None]")
great_expectations/data_context/data_context.py:1978: error: Incompatible types in assignment (expression has type "Union[DatasourceConfig, Dict[str, Union[Dict[str, str], str, Dict[Any, Any]]], Any]", variable has type "DatasourceConfig")
great_expectations/data_context/data_context.py:1979: error: Value of type "Union[Dict[str, DatasourceConfig], Dict[str, Dict[str, Union[Dict[str, str], str, Dict[Any, Any]]]], None]" is not indexable
great_expectations/data_context/data_context.py:3000: error: Incompatible types in assignment (expression has type "Optional[Dict[Any, Any]]", variable has type "Union[CheckpointConfig, Dict[Any, Any]]")
great_expectations/data_context/data_context.py:3028: error: Argument "configuration_key" to "ConfigurationIdentifier" has incompatible type "Optional[str]"; expected "Union[str, UUID]"
great_expectations/data_context/data_context.py:3069: error: Incompatible types in assignment (expression has type "Optional[Dict[Any, Any]]", variable has type "Dict[Any, Any]")
great_expectations/data_context/data_context.py:3089: error: Argument "configuration_key" to "ConfigurationIdentifier" has incompatible type "Optional[str]"; expected "Union[str, UUID]"
great_expectations/data_context/data_context.py:3132: error: Incompatible types in assignment (expression has type "Dict[str, str]", variable has type "Optional[str]")
great_expectations/data_context/data_context.py:3148: error: Argument "run_id" to "run" of "Checkpoint" has incompatible type "Union[str, int, float, None]"; expected "Union[str, RunIdentifier, None]"
great_expectations/data_context/data_context.py:3223: error: List item 0 has incompatible type "Union[DataContextConfig, Dict[Any, Any]]"; expected "Mapping[Any, Any]"
great_expectations/data_context/data_context.py:3235: error: Name "usage_stats_event_payload" already defined on line 3206
great_expectations/data_context/data_context.py:3253: error: Name "usage_stats_event_payload" already defined on line 3206
great_expectations/data_context/data_context.py:3338: error: Item "Dict[Any, Any]" of "Union[CheckpointConfig, Dict[Any, Any]]" has no attribute "to_json_dict"
great_expectations/data_context/data_context.py:3396: error: Name "store_anonymizer" already defined on line 3280
great_expectations/data_context/data_context.py:3399: error: Name "datasource_anonymizer" already defined on line 3301
great_expectations/data_context/data_context.py:3402: error: Name "checkpoint_anonymizer" already defined on line 3350
great_expectations/data_context/data_context.py:3405: error: Name "data_connector_anonymizer" already defined on line 3373
great_expectations/data_context/data_context.py:3414: error: Name "store_name" already defined on line 3269
great_expectations/data_context/data_context.py:3423: error: Name "datasource_name" already defined on line 3289
great_expectations/data_context/data_context.py:3458: error: Name "checkpoint_name" already defined on line 3329
great_expectations/data_context/data_context.py:3462: error: Name "checkpoint_config" already defined on line 3333
great_expectations/data_context/data_context.py:3466: error: Item "Dict[Any, Any]" of "Union[CheckpointConfig, Dict[Any, Any]]" has no attribute "to_json_dict"
great_expectations/data_context/data_context.py:3478: error: Name "data_connector_name" already defined on line 3362
great_expectations/data_context/data_context.py:3492: error: Unsupported operand types for + ("str" and "List[str]")
great_expectations/data_context/data_context.py:3492: note: Left operand is of type "Union[str, List[str]]"
great_expectations/data_context/data_context.py:3521: error: Unsupported operand types for + ("str" and "List[str]")
great_expectations/data_context/data_context.py:3521: note: Left operand is of type "Union[str, List[str]]"
great_expectations/data_context/store/tuple_store_backend.py:218: error: "TupleStoreBackend" has no attribute "_config"; maybe "config"?
great_expectations/data_context/store/tuple_store_backend.py:855: error: Name "_move" already defined on line 817
great_expectations/data_context/store/tuple_store_backend.py:1117: error: "TupleAzureBlobStoreBackend" has no attribute "_config"; maybe "config"?
great_expectations/data_context/store/store_backend.py:217: error: Need type annotation for "_store" (hint: "_store: Dict[<type>, <type>] = ...")
great_expectations/data_context/store/query_store.py:36: error: Incompatible types in assignment (expression has type "Type[StringKey]", base class "Store" defined the type as "Type[DataContextKey]")
great_expectations/data_context/store/metric_store.py:21: error: Incompatible types in assignment (expression has type "Type[ValidationMetricIdentifier]", base class "Store" defined the type as "Type[DataContextKey]")
great_expectations/data_context/store/ge_cloud_store_backend.py:30: error: Argument "manually_initialize_store_backend_id" to "__init__" of "StoreBackend" has incompatible type "Optional[str]"; expected "str"
great_expectations/data_context/store/database_store_backend.py:359: error: Incompatible types in assignment (expression has type "None", variable has type "Callable[[DatabaseStoreBackend], Any]")
great_expectations/data_context/store/checkpoint_store.py:40: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, str]"; expected "Union[int, float, None]"
great_expectations/data_context/store/checkpoint_store.py:40: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, str]"; expected "Optional[Dict[Any, Any]]"
great_expectations/data_context/store/checkpoint_store.py:40: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, str]"; expected "Optional[List[Dict[Any, Any]]]"
great_expectations/data_context/store/checkpoint_store.py:40: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, str]"; expected "Optional[CommentedMap]"
great_expectations/data_context/store/checkpoint_store.py:67: error: Name "test_value" already defined on line 58
great_expectations/core/expectation_suite.py:100: error: Incompatible types in assignment (expression has type "date", variable has type "Union[str, datetime, None]")
great_expectations/core/expectation_suite.py:105: error: Argument "datetime_obj" to "get_datetime_string_from_strftime_format" has incompatible type "Union[str, datetime]"; expected "Optional[datetime]"
great_expectations/core/batch.py:118: error: Incompatible return value type (got "Optional[Dict[Any, Any]]", expected "Dict[Any, Any]")
great_expectations/core/batch.py:202: error: Incompatible return value type (got "Optional[Dict[Any, Any]]", expected "Dict[Any, Any]")
great_expectations/core/batch.py:206: error: Incompatible return value type (got "Optional[Dict[Any, Any]]", expected "Dict[Any, Any]")
great_expectations/core/batch.py:210: error: Incompatible return value type (got "Optional[str]", expected "str")
great_expectations/core/batch.py:214: error: Incompatible return value type (got "Optional[str]", expected "str")
great_expectations/core/batch.py:218: error: Incompatible return value type (got "Optional[str]", expected "str")
great_expectations/core/batch.py:228: error: Incompatible return value type (got "Union[IDDict, Dict[Any, Any], None]", expected "Union[IDDict, Dict[Any, Any]]")
great_expectations/core/batch.py:232: error: Incompatible return value type (got "Optional[int]", expected "int")
great_expectations/core/batch.py:236: error: Incompatible return value type (got "Optional[Dict[Any, Any]]", expected "Dict[Any, Any]")
great_expectations/core/batch.py:301: error: Argument "datasource_name" to "_validate_init_parameters" of "BatchRequest" has incompatible type "Optional[str]"; expected "str"
great_expectations/core/batch.py:302: error: Argument "data_connector_name" to "_validate_init_parameters" of "BatchRequest" has incompatible type "Optional[str]"; expected "str"
great_expectations/core/batch.py:303: error: Argument "data_asset_name" to "_validate_init_parameters" of "BatchRequest" has incompatible type "Optional[str]"; expected "str"
great_expectations/core/batch.py:417: error: Incompatible types in assignment (expression has type "Dict[<nothing>, <nothing>]", variable has type "Optional[BatchRequest]")
great_expectations/core/batch.py:420: error: Incompatible types in assignment (expression has type "IDDict", variable has type "Optional[BatchDefinition]")
great_expectations/core/usage_statistics/usage_statistics.py:48: error: Need type annotation for "_anonymizers" (hint: "_anonymizers: Dict[<type>, <type>] = ...")
great_expectations/checkpoint/util.py:211: error: Incompatible types in assignment (expression has type "Type[BatchRequest]", variable has type "Type[RuntimeBatchRequest]")
great_expectations/checkpoint/util.py:215: error: Incompatible return value type (got "Optional[RuntimeBatchRequest]", expected "Union[BatchRequest, RuntimeBatchRequest]")
great_expectations/checkpoint/configurator.py:134: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, Union[Any, float]]"; expected "Optional[str]"
great_expectations/checkpoint/configurator.py:134: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, Union[Any, float]]"; expected "Optional[Dict[Any, Any]]"
great_expectations/checkpoint/configurator.py:134: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, Union[Any, float]]"; expected "Optional[List[Dict[Any, Any]]]"
great_expectations/checkpoint/configurator.py:134: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, Union[Any, float]]"; expected "Optional[CommentedMap]"
great_expectations/checkpoint/configurator.py:134: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, Union[Any, float]]"; expected "Union[List[Any], str, None]"
great_expectations/checkpoint/configurator.py:157: error: Unsupported target for indexed assignment ("Collection[str]")
great_expectations/checkpoint/checkpoint.py:77: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, Union[str, float, None, BatchRequest, Dict[Any, Any], List[Dict[Any, Any]], UUID]]"; expected "Optional[str]"
great_expectations/checkpoint/checkpoint.py:77: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, Union[str, float, None, BatchRequest, Dict[Any, Any], List[Dict[Any, Any]], UUID]]"; expected "Union[int, float, None]"
great_expectations/checkpoint/checkpoint.py:77: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, Union[str, float, None, BatchRequest, Dict[Any, Any], List[Dict[Any, Any]], UUID]]"; expected "Optional[Dict[Any, Any]]"
great_expectations/checkpoint/checkpoint.py:77: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, Union[str, float, None, BatchRequest, Dict[Any, Any], List[Dict[Any, Any]], UUID]]"; expected "Optional[List[Dict[Any, Any]]]"
great_expectations/checkpoint/checkpoint.py:77: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, Union[str, float, None, BatchRequest, Dict[Any, Any], List[Dict[Any, Any]], UUID]]"; expected "Optional[CommentedMap]"
great_expectations/checkpoint/checkpoint.py:77: error: Argument 1 to "CheckpointConfig" has incompatible type "**Dict[str, Union[str, float, None, BatchRequest, Dict[Any, Any], List[Dict[Any, Any]], UUID]]"; expected "Union[List[Any], str, None]"
great_expectations/checkpoint/checkpoint.py:149: error: Incompatible types in assignment (expression has type "CheckpointConfig", variable has type "None")
great_expectations/checkpoint/checkpoint.py:174: error: Incompatible types in assignment (expression has type "Union[CheckpointConfig, Dict[Any, Any]]", variable has type "None")
great_expectations/checkpoint/checkpoint.py:175: error: Argument "config" to "_substitute_config_variables" of "Checkpoint" has incompatible type "Union[CheckpointConfig, Dict[Any, Any]]"; expected "CheckpointConfig"
great_expectations/checkpoint/checkpoint.py:224: error: Name "runtime_configuration" already defined on line 202
great_expectations/checkpoint/checkpoint.py:225: error: Name "result_format" already defined on line 202
great_expectations/checkpoint/checkpoint.py:225: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "get"
great_expectations/checkpoint/checkpoint.py:229: error: Incompatible types in assignment (expression has type "Dict[str, str]", variable has type "Optional[str]")
great_expectations/checkpoint/checkpoint.py:245: error: Name "run_name_template" already defined on line 202
great_expectations/checkpoint/checkpoint.py:246: error: Name "validations" already defined on line 202
great_expectations/checkpoint/checkpoint.py:247: error: Argument 1 to "len" has incompatible type "Optional[List[Dict[Any, Any]]]"; expected "Sized"
great_expectations/checkpoint/checkpoint.py:254: error: Name "run_name" already defined on line 202
great_expectations/checkpoint/checkpoint.py:255: error: Argument "datetime_obj" to "get_datetime_string_from_strftime_format" has incompatible type "Union[str, datetime]"; expected "Optional[datetime]"
great_expectations/checkpoint/checkpoint.py:260: error: Argument 1 to "enumerate" has incompatible type "Optional[List[Dict[Any, Any]]]"; expected "Iterable[Dict[Any, Any]]"
great_expectations/checkpoint/checkpoint.py:266: error: Name "batch_request" already defined on line 202
great_expectations/checkpoint/checkpoint.py:269: error: Name "expectation_suite_name" already defined on line 202
great_expectations/checkpoint/checkpoint.py:272: error: Name "action_list" already defined on line 202
great_expectations/checkpoint/checkpoint.py:305: error: Argument "run_id" to "CheckpointResult" has incompatible type "Union[str, RunIdentifier]"; expected "RunIdentifier"
great_expectations/checkpoint/checkpoint.py:305: error: Argument "run_results" to "CheckpointResult" has incompatible type "Dict[ValidationResultIdentifier, Dict[str, Union[ExpectationSuiteValidationResult, Dict[Any, Any]]]]"; expected "Dict[ValidationResultIdentifier, Dict[str, Union[ExpectationSuiteValidationResult, Dict[Any, Any], str]]]"
great_expectations/rule_based_profiler/domain_builder/types/domain.py:71: error: Incompatible types in assignment (expression has type "Union[Any, Domain, None]", variable has type "SerializableDotDict")
great_expectations/rule_based_profiler/domain_builder/types/domain.py:117: error: Incompatible return value type (got "Optional[Dict[Any, Any]]", expected "Dict[Any, Any]")
great_expectations/render/view/view.py:438: error: Incompatible types in assignment (expression has type "str", base class "DefaultJinjaView" defined the type as "Type[NoOpTemplate]")
great_expectations/render/view/view.py:449: error: Incompatible types in assignment (expression has type "str", base class "DefaultJinjaView" defined the type as "Type[NoOpTemplate]")
great_expectations/render/view/view.py:458: error: Incompatible types in assignment (expression has type "str", base class "DefaultJinjaView" defined the type as "Type[NoOpTemplate]")
great_expectations/render/view/view.py:471: error: Missing return statement
great_expectations/render/view/view.py:477: error: Incompatible types in assignment (expression has type "str", base class "DefaultJinjaView" defined the type as "Type[NoOpTemplate]")
great_expectations/render/view/view.py:552: error: Incompatible return value type (got "str", expected "Template")
great_expectations/render/view/view.py:552: error: Argument 1 to "Template" has incompatible type "Optional[Any]"; expected "str"
great_expectations/profile/user_configurable_profiler.py:65: error: Incompatible default for argument "primary_or_compound_key" (default has type "bool", argument has type "List[Any]")
great_expectations/profile/user_configurable_profiler.py:107: error: Need type annotation for "column_info" (hint: "column_info: Dict[<type>, <type>] = ...")
great_expectations/profile/json_schema_profiler.py:48: error: Return type "bool" of "validate" incompatible with return type "None" in supertype "Profiler"
great_expectations/profile/json_schema_profiler.py:215: error: Incompatible types in assignment (expression has type "filter[str]", variable has type "List[str]")
great_expectations/profile/json_schema_profiler.py:342: error: Incompatible types in assignment (expression has type "Set[str]", variable has type "List[str]")
great_expectations/data_context/store/util.py:33: error: Item "Dict[Any, Any]" of "Union[StoreBackend, Dict[Any, Any]]" has no attribute "config"
great_expectations/cli/python_subprocess.py:109: error: Item "None" of "Optional[IO[str]]" has no attribute "readline"
great_expectations/cli/python_subprocess.py:116: error: Incompatible types in assignment (expression has type "float", variable has type "int")
great_expectations/cli/python_subprocess.py:118: error: Incompatible types in assignment (expression has type "float", variable has type "int")
great_expectations/cli/python_subprocess.py:120: error: Incompatible types in assignment (expression has type "float", variable has type "int")
great_expectations/cli/python_subprocess.py:122: error: Incompatible types in assignment (expression has type "float", variable has type "int")
great_expectations/cli/python_subprocess.py:128: error: Item "None" of "Optional[IO[str]]" has no attribute "readline"
great_expectations/cli/v012/python_subprocess.py:109: error: Item "None" of "Optional[IO[str]]" has no attribute "readline"
great_expectations/cli/v012/python_subprocess.py:116: error: Incompatible types in assignment (expression has type "float", variable has type "int")
great_expectations/cli/v012/python_subprocess.py:118: error: Incompatible types in assignment (expression has type "float", variable has type "int")
great_expectations/cli/v012/python_subprocess.py:120: error: Incompatible types in assignment (expression has type "float", variable has type "int")
great_expectations/cli/v012/python_subprocess.py:122: error: Incompatible types in assignment (expression has type "float", variable has type "int")
great_expectations/cli/v012/python_subprocess.py:128: error: Item "None" of "Optional[IO[str]]" has no attribute "readline"
great_expectations/rule_based_profiler/util.py:35: error: Argument "batch_request" to "build_batch_request" has incompatible type "Union[BatchRequest, Dict[Any, Any], str]"; expected "Union[Dict[Any, Any], str, None]"
great_expectations/rule_based_profiler/util.py:50: error: Item "None" of "Optional[DataContext]" has no attribute "get_validator"
great_expectations/rule_based_profiler/util.py:68: error: Argument "batch_request" to "build_batch_request" has incompatible type "Union[BatchRequest, Dict[Any, Any], str]"; expected "Union[Dict[Any, Any], str, None]"
great_expectations/rule_based_profiler/util.py:73: error: Item "None" of "Optional[DataContext]" has no attribute "get_batch_list"
great_expectations/rule_based_profiler/util.py:100: error: Argument after ** must be a mapping
great_expectations/rule_based_profiler/parameter_builder/parameter_container.py:104: error: Incompatible types in assignment (expression has type "Union[Any, ParameterNode, None]", variable has type "ParameterNode")
great_expectations/rule_based_profiler/parameter_builder/parameter_container.py:298: error: Incompatible types in assignment (expression has type "Optional[ParameterContainer]", variable has type "ParameterContainer")
great_expectations/rule_based_profiler/parameter_builder/parameter_container.py:301: error: Value of type "Optional[Dict[str, ParameterContainer]]" is not indexable
great_expectations/rule_based_profiler/parameter_builder/parameter_container.py:301: error: Item "None" of "Optional[Domain]" has no attribute "id"
great_expectations/rule_based_profiler/parameter_builder/parameter_container.py:336: error: Unsupported right operand type for in ("Union[Any, ParameterNode, None]")
great_expectations/rule_based_profiler/parameter_builder/parameter_container.py:337: error: Value of type "Union[Any, ParameterNode, None]" is not indexable
great_expectations/rule_based_profiler/parameter_builder/parameter_container.py:345: error: Unsupported right operand type for in ("Optional[ParameterNode]")
great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py:132: error: Argument 1 to "len" has incompatible type "Optional[List[str]]"; expected "Sized"
great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py:140: error: Value of type "Optional[List[str]]" is not indexable
great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py:205: error: Argument 1 to "__call__" of "_UFunc_Nin1_Nout1" has incompatible type "Union[Any, Number]"; expected "Union[int, float, complex, str, bytes, generic]"
great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py:241: error: Name "metric_domain_kwargs" already defined on line 220
great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py:275: error: Unsupported target for indexed assignment ("Union[str, Dict[Any, Any], None]")
great_expectations/rule_based_profiler/parameter_builder/parameter_builder.py:321: error: Incompatible return value type (got "Optional[DataContext]", expected "DataContext")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:121: error: Item "str" of "Union[str, Dict[str, Union[int, None, float, None]]]" has no attribute "keys"
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:167: error: Incompatible types in assignment (expression has type "Optional[Validator]", variable has type "Validator")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:199: error: Incompatible types in assignment (expression has type "Union[ndarray[Any, Any], List[Union[Any, Number]], Dict[str, Any]]", variable has type "Union[ndarray[Any, Any], List[Union[Any, Number]]]")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:200: error: Incompatible types in assignment (expression has type "Union[ndarray[Any, Any], List[Union[Any, Number]], Dict[str, Any]]", variable has type "Dict[str, Any]")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:203: error: Incompatible types in assignment (expression has type "Optional[Any]", variable has type "str")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:230: error: Unsupported operand types for <= ("float" and "str")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:230: note: Right operand is of type "Union[Any, str]"
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:230: error: Unsupported operand types for <= ("str" and "float")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:230: note: Left operand is of type "Union[Any, str]"
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:235: error: Incompatible types in assignment (expression has type "Dict[str, Union[int, None, float, None]]", variable has type "Dict[str, Number]")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:241: error: Incompatible types in assignment (expression has type "Optional[Number]", variable has type "Optional[float]")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:242: error: Incompatible types in assignment (expression has type "Optional[Number]", variable has type "Optional[float]")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:262: error: Argument "false_positive_rate" to "_get_bootstrap_estimate" of "NumericMetricRangeMultiBatchParameterBuilder" has incompatible type "Union[Any, str]"; expected "floating[_64Bit]"
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:270: error: Argument "false_positive_rate" to "compute_quantiles" has incompatible type "Union[Any, str]"; expected "floating[_64Bit]"
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:277: error: Argument 1 to "float" has incompatible type "Union[Number, float]"; expected "Union[SupportsFloat, SupportsIndex, str, bytes]"
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:278: error: Argument 1 to "float" has incompatible type "Union[Number, float]"; expected "Union[SupportsFloat, SupportsIndex, str, bytes]"
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:280: error: Argument 1 to "float" has incompatible type "Union[Number, float]"; expected "Union[SupportsFloat, SupportsIndex, str, bytes]"
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:281: error: Argument 1 to "float" has incompatible type "Union[Number, float]"; expected "Union[SupportsFloat, SupportsIndex, str, bytes]"
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:344: error: Incompatible types in assignment (expression has type "Optional[Any]", variable has type "Dict[str, Optional[Number]]")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:371: error: Unsupported left operand type for > ("Number")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:371: error: No overload variant of "__call__" of "_ComparisonOp" matches argument type "Number"
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:371: note: Possible overload variants:
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:371: note:     def __call__(self, Union[int, float, complex, number[Any], bool_]) -> bool_
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:371: note:     def __call__(self, Union[Union[_SupportsArray[dtype[Union[bool_, number[Any]]]], Sequence[_SupportsArray[dtype[Union[bool_, number[Any]]]]], Sequence[Sequence[_SupportsArray[dtype[Union[bool_, number[Any]]]]]], Sequence[Sequence[Sequence[_SupportsArray[dtype[Union[bool_, number[Any]]]]]]], Sequence[Sequence[Sequence[Sequence[_SupportsArray[dtype[Union[bool_, number[Any]]]]]]]]], Union[bool, int, float, complex, Sequence[Union[bool, int, float, complex]], Sequence[Sequence[Union[bool, int, float, complex]]], Sequence[Sequence[Sequence[Union[bool, int, float, complex]]]], Sequence[Sequence[Sequence[Sequence[Union[bool, int, float, complex]]]]]]]) -> ndarray[Any, dtype[bool_]]
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:371: note: Both left and right operands are unions
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:373: error: Incompatible types in assignment (expression has type "float", variable has type "Optional[Number]")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:375: error: Unsupported left operand type for < ("Number")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:375: error: No overload variant of "__call__" of "_ComparisonOp" matches argument type "Number"
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:375: note: Possible overload variants:
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:375: note:     def __call__(self, Union[int, float, complex, number[Any], bool_]) -> bool_
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:375: note:     def __call__(self, Union[Union[_SupportsArray[dtype[Union[bool_, number[Any]]]], Sequence[_SupportsArray[dtype[Union[bool_, number[Any]]]]], Sequence[Sequence[_SupportsArray[dtype[Union[bool_, number[Any]]]]]], Sequence[Sequence[Sequence[_SupportsArray[dtype[Union[bool_, number[Any]]]]]]], Sequence[Sequence[Sequence[Sequence[_SupportsArray[dtype[Union[bool_, number[Any]]]]]]]]], Union[bool, int, float, complex, Sequence[Union[bool, int, float, complex]], Sequence[Sequence[Union[bool, int, float, complex]]], Sequence[Sequence[Sequence[Union[bool, int, float, complex]]]], Sequence[Sequence[Sequence[Sequence[Union[bool, int, float, complex]]]]]]]) -> ndarray[Any, dtype[bool_]]
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:375: note: Both left and right operands are unions
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:375: error: Unsupported operand type for unary - ("Union[Number, floating[_64Bit]]")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:377: error: Incompatible types in assignment (expression has type "float", variable has type "Optional[Number]")
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:380: error: Dict entry 0 has incompatible type "str": "Optional[Number]"; expected "str": "Optional[float]"
great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py:381: error: Dict entry 1 has incompatible type "str": "Optional[Number]"; expected "str": "Optional[float]"
great_expectations/rule_based_profiler/parameter_builder/metric_parameter_builder.py:71: error: Incompatible types in assignment (expression has type "Optional[Validator]", variable has type "Validator")
great_expectations/rule_based_profiler/parameter_builder/metric_parameter_builder.py:77: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")
great_expectations/rule_based_profiler/domain_builder/simple_semantic_type_domain_builder.py:39: error: Argument "batch_request" to "__init__" of "DomainBuilder" has incompatible type "Union[BatchRequest, Dict[Any, Any], None]"; expected "Union[Dict[Any, Any], str, None]"
great_expectations/rule_based_profiler/domain_builder/simple_semantic_type_domain_builder.py:57: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")
great_expectations/rule_based_profiler/domain_builder/simple_semantic_type_domain_builder.py:58: error: Item "None" of "Optional[Validator]" has no attribute "get_metric"
great_expectations/rule_based_profiler/domain_builder/simple_semantic_type_domain_builder.py:73: error: Item "None" of "Optional[Validator]" has no attribute "get_metric"
great_expectations/rule_based_profiler/domain_builder/simple_semantic_type_domain_builder.py:93: error: Value expression in dictionary comprehension has incompatible type "Union[str, SemanticDomainTypes, None]"; expected type "SemanticDomainTypes"
great_expectations/rule_based_profiler/domain_builder/simple_semantic_type_domain_builder.py:222: error: Item "SemanticDomainTypes" of "Union[str, SemanticDomainTypes]" has no attribute "upper"
great_expectations/rule_based_profiler/domain_builder/simple_semantic_type_domain_builder.py:224: error: Enum index should be a string (actual index type "Union[str, SemanticDomainTypes]")
great_expectations/rule_based_profiler/domain_builder/simple_semantic_type_domain_builder.py:232: error: List comprehension has incompatible type List[Union[str, SemanticDomainTypes]]; expected List[SemanticDomainTypes]
great_expectations/rule_based_profiler/domain_builder/simple_column_suffix_domain_builder.py:30: error: Argument "batch_request" to "__init__" of "DomainBuilder" has incompatible type "Union[BatchRequest, Dict[Any, Any], None]"; expected "Union[Dict[Any, Any], str, None]"
great_expectations/rule_based_profiler/domain_builder/simple_column_suffix_domain_builder.py:55: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")
great_expectations/rule_based_profiler/domain_builder/simple_column_suffix_domain_builder.py:56: error: Item "None" of "Optional[Validator]" has no attribute "get_metric"
great_expectations/rule_based_profiler/domain_builder/domain_builder.py:94: error: Argument 1 to "len" has incompatible type "Optional[List[str]]"; expected "Sized"
great_expectations/rule_based_profiler/domain_builder/domain_builder.py:102: error: Value of type "Optional[List[str]]" is not indexable
great_expectations/rule_based_profiler/domain_builder/column_domain_builder.py:17: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")
great_expectations/rule_based_profiler/domain_builder/column_domain_builder.py:18: error: Item "None" of "Optional[Validator]" has no attribute "get_metric"
great_expectations/render/renderer/page_renderer.py:79: error: Signature of "render" incompatible with supertype "Renderer"
great_expectations/render/renderer/page_renderer.py:115: error: Need type annotation for "columns" (hint: "columns: Dict[<type>, <type>] = ...")
great_expectations/render/renderer/page_renderer.py:229: error: Incompatible types in assignment (expression has type "None", variable has type "datetime")
great_expectations/render/renderer/page_renderer.py:233: error: Incompatible types in assignment (expression has type "None", variable has type "datetime")
great_expectations/render/renderer/notebook_renderer.py:33: error: Name "code" already defined on line 22
great_expectations/render/renderer/notebook_renderer.py:36: error: Value of type "Optional[Any]" is not indexable
great_expectations/render/renderer/notebook_renderer.py:48: error: Value of type "Optional[Any]" is not indexable
great_expectations/render/renderer/content_block/content_block.py:31: error: Need type annotation for "_default_element_styling" (hint: "_default_element_styling: Dict[<type>, <type>] = ...")
great_expectations/self_check/util.py:877: error: Argument 2 to "isinstance" has incompatible type "Optional[Any]"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"
great_expectations/self_check/util.py:881: error: Value of type "Optional[Dict[str, Any]]" is not indexable
great_expectations/self_check/util.py:994: error: Module has no attribute "create_engine"
great_expectations/self_check/util.py:1041: error: Item "None" of "Optional[BatchDefinition]" has no attribute "id"
great_expectations/self_check/util.py:1055: error: Argument 1 to "dict" has incompatible type "List[Tuple[Any, ...]]"; expected "Iterable[Tuple[str, str]]"
great_expectations/self_check/util.py:2003: error: Unsupported left operand type for + ("None")
great_expectations/self_check/util.py:2003: note: Left operand is of type "Optional[str]"
great_expectations/render/renderer/suite_edit_notebook_renderer.py:148: error: Item "None" of "Optional[Environment]" has no attribute "get_template"
great_expectations/render/renderer/suite_edit_notebook_renderer.py:152: error: Item "None" of "Optional[Environment]" has no attribute "get_template"
great_expectations/render/renderer/suite_edit_notebook_renderer.py:271: error: Signature of "render" incompatible with supertype "BaseNotebookRenderer"
great_expectations/render/renderer/suite_edit_notebook_renderer.py:271: error: Signature of "render" incompatible with supertype "Renderer"
great_expectations/render/renderer/suite_edit_notebook_renderer.py:292: error: Signature of "render_to_disk" incompatible with supertype "BaseNotebookRenderer"
great_expectations/render/renderer/datasource_new_notebook_renderer.py:112: error: Signature of "render" incompatible with supertype "Renderer"
great_expectations/render/renderer/checkpoint_new_notebook_renderer.py:22: error: Item "None" of "Optional[DataContext]" has no attribute "datasources"
great_expectations/render/renderer/checkpoint_new_notebook_renderer.py:26: error: Item "LegacyDatasource" of "Union[LegacyDatasource, BaseDatasource, Any]" has no attribute "data_connectors"
great_expectations/render/renderer/checkpoint_new_notebook_renderer.py:36: error: Incompatible return value type (got "Optional[Dict[str, Union[str, Any]]]", expected "Dict[str, str]")
great_expectations/render/renderer/checkpoint_new_notebook_renderer.py:181: error: Signature of "render" incompatible with supertype "Renderer"
great_expectations/render/renderer/content_block/exception_list_content_block.py:12: error: Incompatible types in assignment (expression has type "Type[RenderedBulletListContent]", base class "ContentBlockRenderer" defined the type as "Type[TextContent]")
great_expectations/render/renderer/content_block/exception_list_content_block.py:19: error: Dict entry 1 has incompatible type "str": "Dict[str, str]"; expected "str": "List[str]"
great_expectations/render/renderer/content_block/exception_list_content_block.py:20: error: Dict entry 2 has incompatible type "str": "Dict[str, Collection[str]]"; expected "str": "List[str]"
great_expectations/render/renderer/content_block/exception_list_content_block.py:33: error: Dict entry 3 has incompatible type "str": "Dict[str, List[str]]"; expected "str": "List[str]"
great_expectations/cli/batch_request.py:63: error: Dict entry 1 has incompatible type "str": "Optional[str]"; expected "str": "Union[str, int, Dict[str, Any]]"
great_expectations/cli/batch_request.py:72: error: Argument "data_connector_name" to "_get_data_asset_name_from_data_connector" has incompatible type "Optional[str]"; expected "str"
great_expectations/cli/batch_request.py:76: error: Name "msg_prompt_enter_data_asset_name" already defined on line 69
great_expectations/cli/batch_request.py:81: error: Argument "data_connector_name" to "_get_data_asset_name_for_simple_sqlalchemy_datasource" has incompatible type "Optional[str]"; expected "str"
great_expectations/cli/batch_request.py:102: error: Incompatible types in assignment (expression has type "Union[str, int, Dict[str, Any], None]", variable has type "Dict[str, Union[str, Dict[str, Any]]]")
great_expectations/cli/batch_request.py:113: error: Incompatible return value type (got "Dict[str, Union[str, int, Dict[str, Any]]]", expected "Dict[str, Union[str, Dict[str, Any]]]")
great_expectations/cli/batch_request.py:189: error: Incompatible return value type (got "Optional[str]", expected "str")
great_expectations/cli/batch_request.py:291: error: Incompatible types in assignment (expression has type "Union[str, int, Dict[str, Any]]", variable has type "str")
great_expectations/cli/batch_request.py:292: error: Incompatible types in assignment (expression has type "Union[str, int, Dict[str, Any]]", variable has type "str")
great_expectations/cli/batch_request.py:293: error: Incompatible types in assignment (expression has type "Union[str, int, Dict[str, Any]]", variable has type "str")
great_expectations/cli/batch_request.py:303: error: Incompatible return value type (got "Dict[str, Union[str, int, Dict[str, Any]]]", expected "Dict[str, Union[str, Dict[str, Any]]]")
great_expectations/cli/toolkit.py:131: error: Argument "usage_event" to "tell_user_suite_exists" has incompatible type "Optional[str]"; expected "str"
great_expectations/cli/toolkit.py:135: error: Incompatible types in assignment (expression has type "Optional[ExpectationSuite]", variable has type "ExpectationSuite")
great_expectations/cli/toolkit.py:138: error: Argument "usage_event" to "load_expectation_suite" has incompatible type "Optional[str]"; expected "str"
great_expectations/cli/toolkit.py:156: error: Argument after ** must be a mapping
great_expectations/cli/toolkit.py:178: error: Argument 2 to "getenv" has incompatible type "None"; expected "str"
great_expectations/cli/toolkit.py:293: error: Missing return statement
great_expectations/cli/toolkit.py:341: error: Missing return statement
great_expectations/cli/toolkit.py:403: error: Incompatible types in assignment (expression has type "Union[LegacyDatasource, BaseDatasource, None]", variable has type "Optional[BaseDatasource]")
great_expectations/cli/toolkit.py:405: error: Incompatible return value type (got "Optional[BaseDatasource]", expected "BaseDatasource")
great_expectations/cli/toolkit.py:408: error: Missing return statement
great_expectations/cli/toolkit.py:424: error: Item "CommentedMap" of "Union[DataContextConfig, CommentedMap, Dict[Any, Any], str]" has no attribute "config_version"
great_expectations/cli/toolkit.py:424: error: Item "Dict[Any, Any]" of "Union[DataContextConfig, CommentedMap, Dict[Any, Any], str]" has no attribute "config_version"
great_expectations/cli/toolkit.py:424: error: Item "str" of "Union[DataContextConfig, CommentedMap, Dict[Any, Any], str]" has no attribute "config_version"
great_expectations/cli/toolkit.py:572: error: Bracketed expression "[...]" is not valid as a type
great_expectations/cli/toolkit.py:572: note: Did you mean "List[...]"?
great_expectations/cli/toolkit.py:703: error: Name "filename" already defined on line 700
great_expectations/cli/toolkit.py:704: error: Name "directory" already defined on line 701
great_expectations/cli/toolkit.py:780: error: Argument "usage_event" to "exit_with_failure_message_and_stats" has incompatible type "Optional[str]"; expected "str"
great_expectations/cli/toolkit.py:789: error: Argument "usage_event" to "exit_with_failure_message_and_stats" has incompatible type "Optional[str]"; expected "str"
great_expectations/cli/toolkit.py:802: error: Argument "usage_event" to "exit_with_failure_message_and_stats" has incompatible type "Optional[str]"; expected "str"
great_expectations/cli/toolkit.py:817: error: Argument "usage_event" to "exit_with_failure_message_and_stats" has incompatible type "Optional[str]"; expected "str"
great_expectations/cli/toolkit.py:825: error: Argument "usage_event" to "exit_with_failure_message_and_stats" has incompatible type "Optional[str]"; expected "str"
great_expectations/cli/toolkit.py:860: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, int, Dict[str, Any]]]"; expected "Optional[str]"
great_expectations/cli/toolkit.py:860: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, int, Dict[str, Any]]]"; expected "Union[IDDict, Dict[Any, Any], None]"
great_expectations/cli/toolkit.py:860: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, int, Dict[str, Any]]]"; expected "Optional[int]"
great_expectations/cli/toolkit.py:860: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, int, Dict[str, Any]]]"; expected "Optional[Dict[Any, Any]]"
great_expectations/cli/toolkit.py:864: error: Argument "batch_request" to "add_citation" of "ExpectationSuite" has incompatible type "Dict[str, Union[str, int, Dict[str, Any]]]"; expected "Union[str, Dict[str, Union[str, Dict[str, Any]]], None]"
great_expectations/cli/toolkit.py:883: error: Argument after ** must be a mapping
great_expectations/cli/toolkit.py:891: error: Argument "event" to "send_usage_message" has incompatible type "Optional[str]"; expected "str"
great_expectations/cli/toolkit.py:919: error: Argument "event" to "send_usage_message" has incompatible type "Optional[str]"; expected "str"
great_expectations/cli/toolkit.py:925: error: Incompatible types in assignment (expression has type "Dict[str, Union[str, Dict[str, Any]]]", variable has type "Union[str, Dict[str, Union[str, int, Dict[str, Any]]], None]")
great_expectations/rule_based_profiler/expectation_configuration_builder/default_expectation_configuration_builder.py:35: error: All overload variants of "type" require at least one argument
great_expectations/rule_based_profiler/expectation_configuration_builder/default_expectation_configuration_builder.py:35: note: Possible overload variants:
great_expectations/rule_based_profiler/expectation_configuration_builder/default_expectation_configuration_builder.py:35: note:     def type(self, o: object) -> type
great_expectations/rule_based_profiler/expectation_configuration_builder/default_expectation_configuration_builder.py:35: note:     def type(self, name: str, bases: Tuple[type, ...], dict: Dict[str, Any], **kwds: Any) -> type
great_expectations/rule_based_profiler/expectation_configuration_builder/default_expectation_configuration_builder.py:59: error: Incompatible types in assignment (expression has type "Optional[Any]", variable has type "Dict[str, Any]")
great_expectations/render/renderer/suite_scaffold_notebook_renderer.py:120: error: Signature of "render" incompatible with supertype "SuiteEditNotebookRenderer"
great_expectations/render/renderer/suite_scaffold_notebook_renderer.py:120: error: Signature of "render" incompatible with supertype "Renderer"
great_expectations/render/renderer/suite_scaffold_notebook_renderer.py:153: error: Signature of "render_to_disk" incompatible with supertype "SuiteEditNotebookRenderer"
great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py:26: error: Argument after ** must be a mapping
great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py:122: error: Signature of "render" incompatible with supertype "SuiteEditNotebookRenderer"
great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py:122: error: Signature of "render" incompatible with supertype "Renderer"
great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py:157: error: Signature of "render_to_disk" incompatible with supertype "SuiteEditNotebookRenderer"
great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py:61: error: Name "custom_loader" already defined on line 54
great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py:156: error: Item "None" of "Optional[Environment]" has no attribute "get_template"
great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py:160: error: Item "None" of "Optional[Environment]" has no attribute "get_template"
great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py:297: error: Name "markdown" already defined on line 285
great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py:323: error: Incompatible types in assignment (expression has type "Optional[Dict[Any, Any]]", variable has type "Dict[Any, Any]")
great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py:354: error: Signature of "render" incompatible with supertype "BaseNotebookRenderer"
great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py:354: error: Signature of "render" incompatible with supertype "Renderer"
great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py:374: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, int, Dict[str, Any]]]"; expected "Optional[str]"
great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py:374: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, int, Dict[str, Any]]]"; expected "Union[IDDict, Dict[Any, Any], None]"
great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py:374: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, int, Dict[str, Any]]]"; expected "Optional[int]"
great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py:374: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, int, Dict[str, Any]]]"; expected "Optional[Dict[Any, Any]]"
great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py:376: error: Incompatible types in assignment (expression has type "Dict[str, Union[str, Dict[str, Any]]]", variable has type "Union[str, Dict[str, Union[str, int, Dict[str, Any]]], None]")
great_expectations/render/renderer/v3/suite_edit_notebook_renderer.py:392: error: Signature of "render_to_disk" incompatible with supertype "BaseNotebookRenderer"
great_expectations/render/renderer/content_block/bullet_list_content_block.py:8: error: Incompatible types in assignment (expression has type "Type[RenderedBulletListContent]", base class "ContentBlockRenderer" defined the type as "Type[TextContent]")
great_expectations/expectations/expectation.py:123: error: Need type annotation for "domain_keys"
great_expectations/expectations/expectation.py:124: error: Need type annotation for "success_keys"
great_expectations/expectations/expectation.py:557: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:577: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:594: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:598: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:614: error: "Expectation" has no attribute "expectation_type"
great_expectations/expectations/expectation.py:615: error: "Expectation" has no attribute "expectation_type"
great_expectations/expectations/expectation.py:839: error: "Expectation" has no attribute "examples"; maybe "_get_examples"?
great_expectations/expectations/expectation.py:995: error: Dict entry 0 has incompatible type "str": "Dict[Any, Any]"; expected "str": "str"
great_expectations/expectations/expectation.py:996: error: Dict entry 1 has incompatible type "str": "List[<nothing>]"; expected "str": "str"
great_expectations/expectations/expectation.py:1049: error: Need type annotation for "metric_dependencies"
great_expectations/expectations/expectation.py:1082: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:1083: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:1085: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:1086: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:1088: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:1089: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:1173: error: Incompatible types in assignment (expression has type "Tuple[str, str, str, str, str]", base class "TableExpectation" defined the type as "Tuple[str, str, str, str]")
great_expectations/expectations/expectation.py:1179: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:1188: error: Incompatible types in assignment (expression has type "Tuple[str, str, str, str, str]", base class "TableExpectation" defined the type as "Tuple[str, str, str, str]")
great_expectations/expectations/expectation.py:1208: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:1210: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:1211: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:1342: error: Unsupported left operand type for + ("None")
great_expectations/expectations/expectation.py:1357: error: Unsupported left operand type for - ("None")
great_expectations/expectations/expectation.py:1357: note: Both left and right operands are unions
great_expectations/expectations/expectation.py:1368: error: Unsupported left operand type for + ("None")
great_expectations/expectations/expectation.py:1369: error: Unsupported left operand type for + ("None")
great_expectations/expectations/expectation.py:1371: error: Unsupported left operand type for + ("None")
great_expectations/expectations/expectation.py:1379: error: Incompatible types in assignment (expression has type "Tuple[str, str, str, str, str, str]", base class "TableExpectation" defined the type as "Tuple[str, str, str, str]")
great_expectations/expectations/expectation.py:1405: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:1408: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:1410: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:1411: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/expectation.py:1543: error: Unsupported left operand type for + ("None")
great_expectations/expectations/expectation.py:1558: error: Unsupported left operand type for - ("None")
great_expectations/expectations/expectation.py:1558: note: Both left and right operands are unions
great_expectations/expectations/expectation.py:1569: error: Unsupported left operand type for + ("None")
great_expectations/expectations/expectation.py:1570: error: Unsupported left operand type for + ("None")
great_expectations/expectations/expectation.py:1572: error: Unsupported left operand type for + ("None")
great_expectations/cli/util.py:39: error: Argument "module_names" to "reload_modules" has incompatible type "Optional[List[Any]]"; expected "List[Any]"
great_expectations/cli/suite.py:283: error: Item "str" of "Union[str, Dict[str, Union[str, int, Dict[str, Any]]], None]" has no attribute "get"
great_expectations/cli/suite.py:283: error: Item "None" of "Union[str, Dict[str, Union[str, int, Dict[str, Any]]], None]" has no attribute "get"
great_expectations/cli/suite.py:283: error: Incompatible types in assignment (expression has type "Union[Any, str, int, Dict[str, Any], None]", variable has type "Optional[str]")
great_expectations/cli/suite.py:301: error: Argument "batch_request" to "add_citation_with_batch_request" has incompatible type "Union[str, Dict[str, Union[str, int, Dict[str, Any]]], None]"; expected "Optional[Dict[str, Union[str, int, Dict[str, Any]]]]"
great_expectations/cli/suite.py:309: error: Item "str" of "Union[str, Dict[str, Union[str, int, Dict[str, Any]]]]" has no attribute "get"
great_expectations/cli/suite.py:309: error: Incompatible types in assignment (expression has type "Union[Any, str, int, Dict[str, Any], None]", variable has type "Optional[str]")
great_expectations/cli/suite.py:542: error: Incompatible return value type (got "Optional[bool]", expected "bool")
great_expectations/cli/suite.py:566: error: Incompatible types in assignment (expression has type "None", variable has type "str")
great_expectations/cli/suite.py:568: error: Incompatible types in assignment (expression has type "Optional[ExpectationSuite]", variable has type "ExpectationSuite")
great_expectations/cli/suite.py:581: error: Incompatible types in assignment (expression has type "Union[str, Dict[str, Union[str, int, Dict[str, Any]]], None]", variable has type "Union[str, Dict[str, Union[str, Dict[str, Any]]], None]")
great_expectations/cli/suite.py:596: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, int, Dict[str, Any]]]"; expected "Optional[str]"
great_expectations/cli/suite.py:596: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, int, Dict[str, Any]]]"; expected "Union[IDDict, Dict[Any, Any], None]"
great_expectations/cli/suite.py:596: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, int, Dict[str, Any]]]"; expected "Optional[int]"
great_expectations/cli/suite.py:596: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, int, Dict[str, Any]]]"; expected "Optional[Dict[Any, Any]]"
great_expectations/cli/suite.py:601: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, Dict[str, Any]]]"; expected "Optional[str]"
great_expectations/cli/suite.py:601: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, Dict[str, Any]]]"; expected "Union[IDDict, Dict[Any, Any], None]"
great_expectations/cli/suite.py:601: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, Dict[str, Any]]]"; expected "Optional[int]"
great_expectations/cli/suite.py:601: error: Argument 1 to "BatchRequest" has incompatible type "**Dict[str, Union[str, Dict[str, Any]]]"; expected "Optional[Dict[Any, Any]]"
great_expectations/cli/suite.py:603: error: Incompatible types in assignment (expression has type "Dict[str, Union[str, Dict[str, Any]]]", variable has type "Union[str, Dict[str, Union[str, int, Dict[str, Any]]], None]")
great_expectations/cli/suite.py:619: error: Argument "batch_request" to "add_citation_with_batch_request" has incompatible type "Union[str, Dict[str, Union[str, int, Dict[str, Any]]], None]"; expected "Optional[Dict[str, Union[str, int, Dict[str, Any]]]]"
great_expectations/cli/suite.py:693: error: Argument 1 to "cli_as_deprecation" of "Mark" has incompatible type "Command"; expected "str"
great_expectations/cli/checkpoint.py:268: error: Item "Dict[Any, Any]" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any]]" has no attribute "statistics"
great_expectations/cli/checkpoint.py:275: error: Item "Dict[Any, Any]" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any]]" has no attribute "success"
great_expectations/cli/checkpoint.py:279: error: Item "Dict[Any, Any]" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any]]" has no attribute "meta"
great_expectations/rule_based_profiler/rule/rule.py:42: error: Need type annotation for "_parameters" (hint: "_parameters: Dict[<type>, <type>] = ...")
great_expectations/rule_based_profiler/rule/rule.py:55: error: Item "None" of "Optional[DomainBuilder]" has no attribute "get_domains"
great_expectations/rule_based_profiler/rule/rule.py:66: error: Item "None" of "Optional[List[ParameterBuilder]]" has no attribute "__iter__" (not iterable)
great_expectations/rule_based_profiler/rule/rule.py:77: error: Item "None" of "Optional[List[ExpectationConfigurationBuilder]]" has no attribute "__iter__" (not iterable)
great_expectations/rule_based_profiler/rule/rule.py:91: error: Incompatible return value type (got "Optional[ParameterContainer]", expected "ParameterContainer")
great_expectations/expectations/core/expect_table_row_count_to_equal_other_table.py:139: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_row_count_to_equal.py:93: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_columns_to_match_set.py:88: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_columns_to_match_set.py:90: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_columns_to_match_set.py:91: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_columns_to_match_set.py:93: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_columns_to_match_set.py:95: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_columns_to_match_set.py:166: error: Argument 1 to "set" has incompatible type "Optional[Any]"; expected "Iterable[Any]"
great_expectations/expectations/core/expect_table_columns_to_match_set.py:180: error: Argument 1 to "sorted" has incompatible type "Optional[Any]"; expected "Iterable[Any]"
great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py:99: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py:101: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py:102: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py:104: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py:106: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py:169: error: Argument 1 to "list" has incompatible type "Optional[Any]"; expected "Iterable[Any]"
great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py:174: error: Argument 1 to "list" has incompatible type "Optional[Any]"; expected "Iterable[Any]"
great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py:179: error: Argument 1 to "len" has incompatible type "Optional[Any]"; expected "Sized"
great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py:185: error: Argument 1 to "list" has incompatible type "Optional[Any]"; expected "Iterable[Any]"
great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py:196: error: Argument 1 to "list" has incompatible type "Optional[Any]"; expected "Iterable[Any]"
great_expectations/expectations/core/expect_table_column_count_to_equal.py:95: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_column_count_to_equal.py:98: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_column_count_to_equal.py:100: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_table_column_count_to_equal.py:102: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_select_column_values_to_be_unique_within_record.py:27: error: Need type annotation for "metric_dependencies"
great_expectations/expectations/core/expect_select_column_values_to_be_unique_within_record.py:29: error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_multicolumn_values_to_be_unique.py:23: error: Need type annotation for "metric_dependencies"
great_expectations/expectations/core/expect_multicolumn_values_to_be_unique.py:25: error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_multicolumn_sum_to_equal.py:27: error: Need type annotation for "metric_dependencies"
great_expectations/expectations/core/expect_multicolumn_sum_to_equal.py:29: error: Need type annotation for "default_kwarg_values" (hint: "default_kwarg_values: Dict[<type>, <type>] = ...")
great_expectations/expectations/core/expect_compound_columns_to_be_unique.py:27: error: Need type annotation for "metric_dependencies"
great_expectations/expectations/core/expect_compound_columns_to_be_unique.py:28: error: Incompatible types in assignment (expression has type "Tuple[str]", base class "TableExpectation" defined the type as "Tuple[str, str, str, str]")
great_expectations/expectations/core/expect_column_values_to_not_match_regex_list.py:72: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_not_match_regex_list.py:74: error: Incompatible types in assignment (expression has type "Tuple[str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_not_match_regex.py:97: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_not_match_regex.py:99: error: Incompatible types in assignment (expression has type "Tuple[str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern_list.py:68: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern_list.py:70: error: Incompatible types in assignment (expression has type "Tuple[str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern_list.py:88: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern_list.py:91: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern_list.py:93: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern_list.py:94: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern_list.py:96: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern_list.py:97: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern.py:68: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern.py:70: error: Incompatible types in assignment (expression has type "Tuple[str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern.py:87: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern.py:89: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern.py:91: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_not_match_like_pattern.py:92: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_not_be_null.py:75: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py:94: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py:96: error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_not_be_in_set.py:227: error: "Type[PandasExecutionEngine]" has no attribute "parse_value_set"
great_expectations/expectations/core/expect_column_values_to_match_strftime_format.py:67: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_match_strftime_format.py:69: error: Incompatible types in assignment (expression has type "Tuple[str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_match_regex_list.py:79: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_match_regex_list.py:81: error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_match_regex.py:79: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_match_regex.py:81: error: Incompatible types in assignment (expression has type "Tuple[str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_match_like_pattern_list.py:22: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_match_like_pattern_list.py:23: error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_match_like_pattern_list.py:40: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_match_like_pattern_list.py:43: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_match_like_pattern_list.py:45: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_match_like_pattern_list.py:46: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_match_like_pattern_list.py:48: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_match_like_pattern_list.py:49: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_match_like_pattern.py:27: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_match_like_pattern.py:29: error: Incompatible types in assignment (expression has type "Tuple[str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_match_like_pattern.py:46: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_match_like_pattern.py:48: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_match_like_pattern.py:50: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_match_like_pattern.py:51: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_match_json_schema.py:76: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_match_json_schema.py:78: error: Incompatible types in assignment (expression has type "Tuple[str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_be_unique.py:83: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_be_unique.py:100: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_unique.py:102: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_unique.py:103: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_of_type.py:72: error: List or tuple literal expected as the second argument to namedtuple()
great_expectations/expectations/core/expect_column_values_to_be_of_type.py:75: error: Too many arguments for "BigQueryTypes"
great_expectations/expectations/core/expect_column_values_to_be_of_type.py:145: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_be_of_type.py:147: error: Incompatible types in assignment (expression has type "Tuple[str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_be_of_type.py:161: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_of_type.py:335: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_of_type.py:336: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_of_type.py:346: error: Argument "metric_domain_kwargs" to "MetricConfiguration" has incompatible type "Optional[Any]"; expected "Dict[Any, Any]"
great_expectations/expectations/core/expect_column_values_to_be_of_type.py:396: error: Item "None" of "Optional[Any]" has no attribute "__iter__" (not iterable)
great_expectations/expectations/core/expect_column_values_to_be_null.py:72: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_be_json_parseable.py:86: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_be_increasing.py:81: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_be_increasing.py:82: error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_be_in_set.py:101: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_be_in_set.py:103: error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_be_in_set.py:258: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_in_set.py:260: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_in_set.py:261: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_in_set.py:263: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_in_set.py:265: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_decreasing.py:82: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_be_decreasing.py:84: error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_be_dateutil_parseable.py:77: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_be_between.py:87: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_be_between.py:89: error: Incompatible types in assignment (expression has type "Tuple[str, str, str, str, str, str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_be_between.py:131: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_between.py:132: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_between.py:133: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_between.py:134: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_value_lengths_to_equal.py:72: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_value_lengths_to_equal.py:73: error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py:100: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py:102: error: Incompatible types in assignment (expression has type "Tuple[str, str, str, str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_value_lengths_to_be_between.py:184: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_to_exist.py:64: error: Incompatible types in assignment (expression has type "Tuple[str, str]", base class "TableExpectation" defined the type as "Tuple[str, str, str, str]")
great_expectations/expectations/core/expect_column_to_exist.py:89: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_to_exist.py:91: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_to_exist.py:94: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_to_exist.py:95: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_to_exist.py:97: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_to_exist.py:98: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_to_exist.py:165: error: Value of type "Optional[Any]" is not indexable
great_expectations/expectations/core/expect_column_to_exist.py:169: error: Unsupported right operand type for in ("Optional[Any]")
great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py:149: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py:152: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py:159: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py:162: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py:163: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py:369: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py:393: error: Value of type "Optional[Any]" is not indexable
great_expectations/expectations/core/expect_column_parameterized_distribution_ks_test_p_value_to_be_greater_than.py:29: error: Need type annotation for "metric_dependencies"
great_expectations/expectations/core/expect_column_parameterized_distribution_ks_test_p_value_to_be_greater_than.py:31: error: Need type annotation for "default_kwarg_values" (hint: "default_kwarg_values: Dict[<type>, <type>] = ...")
great_expectations/expectations/core/expect_column_pair_values_to_be_in_set.py:78: error: Incompatible types in assignment (expression has type "Tuple[str]", base class "ColumnPairMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_pair_values_to_be_in_set.py:80: error: Incompatible types in assignment (expression has type "Tuple[str, str, str, str, str, str]", base class "TableExpectation" defined the type as "Tuple[str, str, str, str]")
great_expectations/expectations/core/expect_column_pair_values_to_be_in_set.py:87: error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "ColumnPairMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_pair_cramers_phi_value_to_be_less_than.py:26: error: Need type annotation for "metric_dependencies"
great_expectations/expectations/core/expect_column_most_common_value_to_be_in_set.py:190: error: Argument 1 to "intersection" of "set" has incompatible type "Optional[Any]"; expected "Iterable[Any]"
great_expectations/expectations/core/expect_column_most_common_value_to_be_in_set.py:195: error: Argument 1 to "len" has incompatible type "Optional[Any]"; expected "Sized"
great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py:199: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py:200: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "get_domain_kwargs"
great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py:204: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py:226: error: Argument "execution_engine" to "build_metric_dependency_graph" of "Validator" has incompatible type "Optional[ExecutionEngine]"; expected "ExecutionEngine"
great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py:602: error: Value of type "float" is not indexable
great_expectations/expectations/core/expect_column_distinct_values_to_equal_set.py:143: error: Item "None" of "Optional[Any]" has no attribute "index"
great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py:53: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py:55: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py:57: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py:59: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py:147: error: Item "None" of "Optional[Any]" has no attribute "index"
great_expectations/expectations/core/expect_column_distinct_values_to_contain_set.py:151: error: Item "None" of "Optional[Any]" has no attribute "index"
great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py:277: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py:279: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py:280: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py:282: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py:284: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py:301: error: Item "None" of "Optional[Any]" has no attribute "index"
great_expectations/expectations/core/expect_column_chisquare_test_p_value_to_be_greater_than.py:27: error: Need type annotation for "metric_dependencies"
great_expectations/expectations/core/expect_column_chisquare_test_p_value_to_be_greater_than.py:29: error: Need type annotation for "default_kwarg_values" (hint: "default_kwarg_values: Dict[<type>, <type>] = ...")
great_expectations/expectations/core/expect_column_bootstrapped_ks_test_p_value_to_be_greater_than.py:27: error: Need type annotation for "metric_dependencies"
great_expectations/expectations/core/expect_column_bootstrapped_ks_test_p_value_to_be_greater_than.py:29: error: Need type annotation for "default_kwarg_values" (hint: "default_kwarg_values: Dict[<type>, <type>] = ...")
great_expectations/cli/datasource.py:192: error: Incompatible types in assignment (expression has type "Union[MySQLCredentialYamlHelper, PostgresCredentialYamlHelper, RedshiftCredentialYamlHelper, SnowflakeCredentialYamlHelper, BigqueryCredentialYamlHelper, ConnectionStringCredentialYamlHelper]", variable has type "Union[PandasYamlHelper, SparkYamlHelper]")
great_expectations/cli/datasource.py:692: error: Incompatible return value type (got "SQLCredentialYamlHelper", expected "Union[MySQLCredentialYamlHelper, PostgresCredentialYamlHelper, RedshiftCredentialYamlHelper, SnowflakeCredentialYamlHelper, BigqueryCredentialYamlHelper, ConnectionStringCredentialYamlHelper]")
great_expectations/cli/datasource.py:718: error: Incompatible return value type (got "FilesYamlHelper", expected "Union[PandasYamlHelper, SparkYamlHelper]")
great_expectations/cli/v012/util.py:19: error: Incompatible types in assignment (expression has type "None", variable has type "Callable[[str, Optional[str], Optional[str], Optional[Iterable[str]]], str]")
great_expectations/cli/v012/util.py:151: error: Argument "module_names" to "reload_modules" has incompatible type "Optional[List[Any]]"; expected "List[Any]"
great_expectations/cli/v012/toolkit.py:319: error: Missing return statement
great_expectations/cli/v012/toolkit.py:353: error: Missing return statement
great_expectations/cli/v012/toolkit.py:412: error: Incompatible return value type (got "Union[LegacyDatasource, BaseDatasource, None]", expected "Datasource")
great_expectations/cli/v012/toolkit.py:415: error: Missing return statement
great_expectations/cli/v012/toolkit.py:421: error: Item "CommentedMap" of "Union[DataContextConfig, CommentedMap, Dict[Any, Any], str]" has no attribute "config_version"
great_expectations/cli/v012/toolkit.py:421: error: Item "Dict[Any, Any]" of "Union[DataContextConfig, CommentedMap, Dict[Any, Any], str]" has no attribute "config_version"
great_expectations/cli/v012/toolkit.py:421: error: Item "str" of "Union[DataContextConfig, CommentedMap, Dict[Any, Any], str]" has no attribute "config_version"
great_expectations/cli/v012/toolkit.py:465: error: "PluginModuleNotFoundError" has no attribute "cli"
great_expectations/cli/v012/toolkit.py:468: error: "PluginClassNotFoundError" has no attribute "cli"
great_expectations/cli/v012/toolkit.py:538: error: Bracketed expression "[...]" is not valid as a type
great_expectations/cli/v012/toolkit.py:538: note: Did you mean "List[...]"?
great_expectations/cli/v012/checkpoint.py:243: error: Item "Dict[Any, Any]" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any]]" has no attribute "statistics"
great_expectations/cli/v012/checkpoint.py:250: error: Item "Dict[Any, Any]" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any]]" has no attribute "success"
great_expectations/cli/v012/checkpoint.py:254: error: Item "Dict[Any, Any]" of "Union[ExpectationSuiteValidationResult, Dict[Any, Any]]" has no attribute "meta"
great_expectations/rule_based_profiler/profiler.py:118: error: Item "None" of "Optional[Dict[str, Dict[str, Dict[str, Any]]]]" has no attribute "get"
great_expectations/rule_based_profiler/profiler.py:125: error: Incompatible types in assignment (expression has type "Optional[Any]", variable has type "Dict[Any, Any]")
great_expectations/rule_based_profiler/profiler.py:142: error: Incompatible types in assignment (expression has type "Optional[Any]", variable has type "Dict[Any, Any]")
great_expectations/rule_based_profiler/profiler.py:161: error: Incompatible types in assignment (expression has type "Optional[Any]", variable has type "Dict[Any, Any]")
great_expectations/rule_based_profiler/profiler.py:181: error: Item "None" of "Optional[Dict[str, Dict[str, Dict[str, Any]]]]" has no attribute "get"
great_expectations/rule_based_profiler/profiler.py:182: error: Argument 2 to "get" of "Mapping" has incompatible type "Dict[<nothing>, <nothing>]"; expected "Union[Dict[str, Dict[str, Any]], Dict[str, Dict[Any, Any]]]"
great_expectations/render/renderer/content_block/validation_results_table_content_block.py:25: error: Incompatible types in assignment (expression has type "Type[RenderedTableContent]", base class "ContentBlockRenderer" defined the type as "Type[TextContent]")
great_expectations/render/renderer/content_block/validation_results_table_content_block.py:36: error: Dict entry 0 has incompatible type "str": "Dict[str, List[str]]"; expected "str": "List[str]"
great_expectations/expectations/metrics/metric_provider.py:39: error: "Callable[[VarArg(Any), KwArg(Any)], Any]" has no attribute "metric_engine"
great_expectations/expectations/metrics/metric_provider.py:40: error: "Callable[[VarArg(Any), KwArg(Any)], Any]" has no attribute "metric_fn_type"
great_expectations/expectations/metrics/metric_provider.py:41: error: "Callable[[VarArg(Any), KwArg(Any)], Any]" has no attribute "metric_definition_kwargs"
great_expectations/expectations/metrics/metric_provider.py:60: error: "Callable[[VarArg(Any), KwArg(Any)], Any]" has no attribute "metric_engine"
great_expectations/expectations/metrics/metric_provider.py:61: error: "Callable[[VarArg(Any), KwArg(Any)], Any]" has no attribute "metric_fn_type"
great_expectations/expectations/metrics/metric_provider.py:64: error: "Callable[[VarArg(Any), KwArg(Any)], Any]" has no attribute "domain_type"
great_expectations/expectations/metrics/metric_provider.py:65: error: "Callable[[VarArg(Any), KwArg(Any)], Any]" has no attribute "metric_definition_kwargs"
great_expectations/expectations/metrics/metric_provider.py:100: error: Need type annotation for "domain_keys"
great_expectations/expectations/metrics/metric_provider.py:101: error: Need type annotation for "value_keys"
great_expectations/expectations/metrics/metric_provider.py:102: error: Need type annotation for "default_kwarg_values" (hint: "default_kwarg_values: Dict[<type>, <type>] = ...")
great_expectations/expectations/metrics/map_metric_provider.py:60: error: Incompatible types in assignment (expression has type "MetricPartialFunctionTypes", variable has type "Optional[str]")
great_expectations/expectations/metrics/map_metric_provider.py:61: error: Incompatible types in assignment (expression has type "MetricPartialFunctionTypes", variable has type "Optional[str]")
great_expectations/expectations/metrics/map_metric_provider.py:70: error: Argument "partial_fn_type" to "metric_partial" has incompatible type "Optional[str]"; expected "Union[str, MetricPartialFunctionTypes]"
great_expectations/expectations/metrics/map_metric_provider.py:119: error: Incompatible types in assignment (expression has type "MetricPartialFunctionTypes", variable has type "Optional[str]")
great_expectations/expectations/metrics/map_metric_provider.py:120: error: Incompatible types in assignment (expression has type "MetricPartialFunctionTypes", variable has type "Optional[str]")
great_expectations/expectations/metrics/map_metric_provider.py:129: error: Argument "partial_fn_type" to "metric_partial" has incompatible type "Optional[str]"; expected "Union[str, MetricPartialFunctionTypes]"
great_expectations/expectations/metrics/map_metric_provider.py:184: error: Incompatible types in assignment (expression has type "MetricPartialFunctionTypes", variable has type "Optional[str]")
great_expectations/expectations/metrics/map_metric_provider.py:185: error: Incompatible types in assignment (expression has type "MetricPartialFunctionTypes", variable has type "Optional[str]")
great_expectations/expectations/metrics/map_metric_provider.py:197: error: Argument "partial_fn_type" to "metric_partial" has incompatible type "Optional[str]"; expected "Union[str, MetricPartialFunctionTypes]"
great_expectations/expectations/metrics/map_metric_provider.py:291: error: Argument "partial_fn_type" to "metric_partial" has incompatible type "Union[str, MetricPartialFunctionTypes, None]"; expected "Union[str, MetricPartialFunctionTypes]"
great_expectations/expectations/metrics/map_metric_provider.py:357: error: Argument "partial_fn_type" to "metric_partial" has incompatible type "Union[str, MetricPartialFunctionTypes, None]"; expected "Union[str, MetricPartialFunctionTypes]"
great_expectations/expectations/metrics/map_metric_provider.py:434: error: Argument "partial_fn_type" to "metric_partial" has incompatible type "Union[str, MetricPartialFunctionTypes, None]"; expected "Union[str, MetricPartialFunctionTypes]"
great_expectations/expectations/metrics/map_metric_provider.py:654: error: "None" object is not iterable
great_expectations/expectations/metrics/map_metric_provider.py:704: error: "None" object is not iterable
great_expectations/expectations/metrics/map_metric_provider.py:773: error: "None" object is not iterable
great_expectations/expectations/metrics/map_metric_provider.py:819: error: "None" object is not iterable
great_expectations/expectations/metrics/map_metric_provider.py:845: error: "None" object is not iterable
great_expectations/expectations/metrics/map_metric_provider.py:927: error: "None" object is not iterable
great_expectations/expectations/metrics/map_metric_provider.py:974: error: "None" object is not iterable
great_expectations/expectations/metrics/map_metric_provider.py:1015: error: "None" object is not iterable
great_expectations/expectations/metrics/map_metric_provider.py:1043: error: "None" object is not iterable
great_expectations/expectations/metrics/map_metric_provider.py:1062: error: "None" object is not iterable
great_expectations/expectations/metrics/map_metric_provider.py:1082: error: "None" object is not iterable
great_expectations/expectations/metrics/map_metric_provider.py:1124: error: "None" object is not iterable
great_expectations/expectations/metrics/map_metric_provider.py:1164: error: "None" object is not iterable
great_expectations/expectations/metrics/map_metric_provider.py:1195: error: Need type annotation for "condition_value_keys"
great_expectations/expectations/metrics/map_metric_provider.py:1196: error: Need type annotation for "function_value_keys"
great_expectations/expectations/metrics/map_metric_provider.py:1529: error: Incompatible types in assignment (expression has type "Tuple[str, str, str, str, str]", base class "MapMetricProvider" defined the type as "Tuple[str, str, str, str]")
great_expectations/expectations/metrics/map_metric_provider.py:1536: error: Incompatible types in assignment (expression has type "Tuple[str, str, str, str, str]", base class "MapMetricProvider" defined the type as "Tuple[str, str, str, str]")
great_expectations/expectations/metrics/map_metric_provider.py:1542: error: Need type annotation for "condition_value_keys"
great_expectations/expectations/metrics/map_metric_provider.py:1543: error: Need type annotation for "function_value_keys"
great_expectations/expectations/metrics/column_aggregate_metric.py:234: error: Incompatible types in assignment (expression has type "Tuple[str, str, str, str, str]", base class "TableMetricProvider" defined the type as "Tuple[str, str, str, str]")
great_expectations/expectations/metrics/table_metrics/table_columns.py:35: error: Invalid index type "str" for "Dict[Tuple[Any, ...], Any]"; expected type "Tuple[Any, ...]"
great_expectations/expectations/metrics/table_metrics/table_columns.py:47: error: Invalid index type "str" for "Dict[Tuple[Any, ...], Any]"; expected type "Tuple[Any, ...]"
great_expectations/expectations/metrics/table_metrics/table_columns.py:59: error: Invalid index type "str" for "Dict[Tuple[Any, ...], Any]"; expected type "Tuple[Any, ...]"
great_expectations/expectations/metrics/table_metrics/table_column_count.py:30: error: No overload variant of "get" of "Mapping" matches argument type "str"
great_expectations/expectations/metrics/table_metrics/table_column_count.py:30: note: Possible overload variant:
great_expectations/expectations/metrics/table_metrics/table_column_count.py:30: note:     def get(self, key: Tuple[Any, ...]) -> Optional[Any]
great_expectations/expectations/metrics/table_metrics/table_column_count.py:30: note:     <1 more non-matching overload not shown>
great_expectations/expectations/metrics/table_metrics/table_column_count.py:42: error: No overload variant of "get" of "Mapping" matches argument type "str"
great_expectations/expectations/metrics/table_metrics/table_column_count.py:42: note: Possible overload variant:
great_expectations/expectations/metrics/table_metrics/table_column_count.py:42: note:     def get(self, key: Tuple[Any, ...]) -> Optional[Any]
great_expectations/expectations/metrics/table_metrics/table_column_count.py:42: note:     <1 more non-matching overload not shown>
great_expectations/expectations/metrics/table_metrics/table_column_count.py:54: error: No overload variant of "get" of "Mapping" matches argument type "str"
great_expectations/expectations/metrics/table_metrics/table_column_count.py:54: note: Possible overload variant:
great_expectations/expectations/metrics/table_metrics/table_column_count.py:54: note:     def get(self, key: Tuple[Any, ...]) -> Optional[Any]
great_expectations/expectations/metrics/table_metrics/table_column_count.py:54: note:     <1 more non-matching overload not shown>
great_expectations/expectations/metrics/column_map_metrics/column_values_z_score.py:33: error: Need type annotation for "function_value_keys"
great_expectations/expectations/metrics/column_map_metrics/column_values_increasing.py:61: error: Invalid index type "str" for "Dict[Tuple[Any, ...], Any]"; expected type "Tuple[Any, ...]"
great_expectations/expectations/metrics/column_map_metrics/column_values_decreasing.py:56: error: Invalid index type "str" for "Dict[Tuple[Any, ...], Any]"; expected type "Tuple[Any, ...]"
great_expectations/expectations/metrics/column_aggregate_metrics/column_quantile_values.py:318: error: Name "quantiles_results" already defined on line 302
great_expectations/expectations/metrics/column_aggregate_metrics/column_most_common_value.py:40: error: No overload variant of "get" of "Mapping" matches argument type "str"
great_expectations/expectations/metrics/column_aggregate_metrics/column_most_common_value.py:40: note: Possible overload variant:
great_expectations/expectations/metrics/column_aggregate_metrics/column_most_common_value.py:40: note:     def get(self, key: Tuple[Any, ...]) -> Optional[Any]
great_expectations/expectations/metrics/column_aggregate_metrics/column_most_common_value.py:40: note:     <1 more non-matching overload not shown>
great_expectations/expectations/metrics/column_aggregate_metrics/column_most_common_value.py:54: error: No overload variant of "get" of "Mapping" matches argument type "str"
great_expectations/expectations/metrics/column_aggregate_metrics/column_most_common_value.py:54: note: Possible overload variant:
great_expectations/expectations/metrics/column_aggregate_metrics/column_most_common_value.py:54: note:     def get(self, key: Tuple[Any, ...]) -> Optional[Any]
great_expectations/expectations/metrics/column_aggregate_metrics/column_most_common_value.py:54: note:     <1 more non-matching overload not shown>
great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py:60: error: No overload variant of "get" of "Mapping" matches argument type "str"
great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py:60: note: Possible overload variant:
great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py:60: note:     def get(self, key: Tuple[Any, ...]) -> Optional[Any]
great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py:60: note:     <1 more non-matching overload not shown>
great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py:117: error: No overload variant of "get" of "Mapping" matches argument type "str"
great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py:117: note: Possible overload variant:
great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py:117: note:     def get(self, key: Tuple[Any, ...]) -> Optional[Any]
great_expectations/expectations/metrics/column_aggregate_metrics/column_median.py:117: note:     <1 more non-matching overload not shown>
great_expectations/expectations/metrics/column_aggregate_metrics/column_distinct_values.py:36: error: Invalid index type "str" for "Dict[Tuple[Any, ...], Any]"; expected type "Tuple[Any, ...]"
great_expectations/expectations/metrics/column_aggregate_metrics/column_distinct_values.py:48: error: Invalid index type "str" for "Dict[Tuple[Any, ...], Any]"; expected type "Tuple[Any, ...]"
great_expectations/expectations/metrics/column_aggregate_metrics/column_distinct_values.py:99: error: Invalid index type "str" for "Dict[Tuple[Any, ...], Any]"; expected type "Tuple[Any, ...]"
great_expectations/expectations/metrics/column_aggregate_metrics/column_distinct_values.py:111: error: Invalid index type "str" for "Dict[Tuple[Any, ...], Any]"; expected type "Tuple[Any, ...]"
great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py:104: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py:107: error: Incompatible types in assignment (expression has type "Tuple[str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py:121: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py:123: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py:124: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py:126: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py:128: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py:336: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py:337: error: Item "None" of "Optional[ExpectationConfiguration]" has no attribute "kwargs"
great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py:347: error: Argument "metric_domain_kwargs" to "MetricConfiguration" has incompatible type "Optional[Any]"; expected "Dict[Any, Any]"
great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py:395: error: Item "None" of "Optional[Any]" has no attribute "__iter__" (not iterable)
great_expectations/expectations/core/expect_column_value_z_scores_to_be_less_than.py:69: error: Incompatible types in assignment (expression has type "str", base class "ColumnMapExpectation" defined the type as "None")
great_expectations/expectations/core/expect_column_value_z_scores_to_be_less_than.py:70: error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "ColumnMapExpectation" defined the type as "Tuple[str]")
great_expectations/jupyter_ux/__init__.py:62: error: Not all arguments converted during string formatting
Found 897 errors in 158 files (checked 394 source files)
